### ISSUE TITLE
Bars below piano roll notes for graphical P field editing [sf#10]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#10]
It would be great to have vertical bars below piano 
roll notes for graphical P field editing, with the 
ability to switch between which P field was being 
displayed - similar to velocity and controller editing 
in MIDI sequencers. This would be a great help when 
working with complex instruments.

**Comment by tjingboem** [comment]
the format of the PianoRoll for events is
i -INSTR_ID- -START- -DUR -FREQ-
Perhaps a new blue variable can be created -VEL- for velocity, that can be an optional one
to be set as p5 (or whatever p field you'd like):
i -INSTR_ID- -START- -DUR- -FREQ- -VEL-
it could correspond to a 'velocity bar' at the bottom of the PianoRoll. Those value can in turn scale the -VEL- value (0 - 1)

A bar like the one in Reaper:
![MidiReaper](https://user-images.githubusercontent.com/6670911/83518798-3576e980-a4db-11ea-91ba-8c1f4ef62dd2.png)

**Comment by kunstmusik** [comment]
Closed as implemented for 2.8.1.
