### ISSUE TITLE
copy Automation Lines [sf#145]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#145]
i have a SoundObject with Automation Lines that i like very much. I would like to copy this

Can Automation Lines be copied within the selection of the Multi Line and pasted elsewhere at the moment?

**Comment by tjingboem** [comment]
i think this request is obsolete, because i have requested a similar thing with # 330.
So this issue can be closed.

**Comment by kunstmusik** [comment]
Marked as duplicate and we can track this work in #330.  Thanks!
