### ISSUE TITLE
undo function? [sf#146]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#146]
For undo, Netbeans has an entire Undo system that I have not tied all
of Blue into. It's a bit complicated but there are some differences in
the models of how GUI components handle undoability and what I had
built in the Blue 1.x series.  So some components have undo/redo that
are self contained, while others are managed through the global
undo/redo options

**Comment by tjingboem** [comment]
there is undoability in the Score, but not yet in Single Line and Multi Line mode.

**Comment by kunstmusik** [comment]
Closing as completed for 2.8.0.
