### ISSUE TITLE
Precision-value in JMask SoundObject [sf#152]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#152]
I would like to ask for a possibility to add a precision-value after each parameter (except of constant). 

See the excerpt of the Cmask-manual:
"  prec <val>
The numbers computed by the last modul of every parameter will be rounded normally to a precision of 5, that is 5 decimal places after the point. This precision in changeable with the optional prec - value (0...5). <val> defines the desired number of decimal places for the output, 0 results in integers, negative values are not allowed."

Maybe it could be done by adding a checkbox beneath the checkboxes for "Quantize" and "Accumulator". Likewise a new area would show up with a little dropdown menu, where the precision-value could be chosen.

**Comment by tjingboem** [comment]
This issue can be closed, as this is possible already:
![Screenshot from 2019-11-13 13-44-46](https://user-images.githubusercontent.com/6670911/68764923-ee4b0900-061b-11ea-8820-2671be151dd6.png)

Precision can be set by Grid Size in the Quantizer. Here the result when Grid Size has 0.001 resolution:
![Screenshot from 2019-11-13 13-45-06](https://user-images.githubusercontent.com/6670911/68765036-25211f00-061c-11ea-94a8-e0ec2adfb78a.png)
