### ISSUE TITLE
switch between projects [sf#83]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#235]
sometimes - not always - i find that it is not possible to select Objects.
This happens when i go to another open blue project window and go back to the blue project i am working on.
I am atm switching between projects because i want to start all over again with the same piece, but this time staring with a clean window. I copy Objects from the "old" blue project, paste into the new. Then, it happens, that i am unable to select an Object in the new window.
When i close the "old" project window, i can fully access the new project window.

**Comment by tjingboem** [comment]
i have not encountered this problem in a while - if you agree, it is save to close this bug

**Comment by kunstmusik** [comment]
Okay, I will close this and you can file a new issue if this happens again.
