### ISSUE TITLE
multiline rectangle remains [sf#95]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#247]
I dragged an Object and its automation lines to the left but the white box remains visible, even after having done some changes in the score afterwards. 
This is not always the case - sometimes it vanishes when it should.

**Comment by tjingboem** [comment]
i have not encountered this problem in a while - if you agree, it is save to close this bug

**Comment by kunstmusik** [comment]
Okay, I'm actually working on redoing multiline mode, but I'll hopefully have everything setup to work correctly.  I'll close this issue.
