### ISSUE TITLE
When auditioning SoundObjects inside a PolyObject, BlueMixer automation settings are wrong.

### ISSUE THREAD

**Issue by fcahoon** [kunstmusik/blue#248]
When using BlueMixer automations, there is a problem auditioning SoundObjects inside a PolyObject: The audition will play using the BlueMixer automation settings at the root level at the beginning of the piece.  For example, if you have the Volume all the way down at the beginning, and have the PolyObject fade in some time later in the piece, you won't hear anything when you audition the components of that PolyObject, because it will erroneously use the Volume setting from the beginning of the piece.

A workaround is to disable BlueMixer while auditioning -- which is actually working fine for me, so I don't consider this a high-priority bug.

**Comment by kunstmusik** [comment]
I've implemented a partial fix.  There were two issues: 

1. Mixer automations were not being used at all, so only the initial value was used.  I've redid the code for automation to ensure automations are being used. 
2. The auditioning of SoundObjects within PolyObjects is highly problematic.  I spent a good couple of hours on this and there problem is that there are a number of transformations that occur that require rendering the entire PolyObject out first before processing.  For example, NoteProcessors may modify the generated score for the PolyObject containing the selected objects, Also, time behavior of SCALE adjusts time according to the entire score generated by all objects within the PolyObject.  Considering PolyObjects can be embedded numerous levels, the process of calculating just the score for the selected objects, as well as calculating start/end times became onerous.  (Another issue is that if a SoundObject uses a time behavior of NONE, then there's no knowledge of how to calculate times without first generating the entire score).  

The fix I put in will at least respect automations when auditioning ScoreObjects on the root level of the timeline.  This seems like an improvement.  The latter part of dealing with SoundObjects will require some fundamental changes to Blue. Blue 3.0 already has in mind to make big adjustments to the internal rendering system.  

I have filed issue #333 to continue this work in the Blue 3.0 timeframe and have made a reference to this ticket.  For 2.6.1, the adjusted behavior for respecting automations is in place so I will close this ticket and resume work in #333. 

Thanks for filing this @fcahoon !

steven
