### ISSUE TITLE
In line point editor for parameter automation, position of the last point can't be edited

### ISSUE THREAD

**Issue by fcahoon** [kunstmusik/blue#249]
When I'm editing automation parameters manually using the line point editor, the position of the last point can't be edited. When I click on any other cell of the table, I get a blinking cursor in front of the number and can edit it. The position of the last point never gives me a cursor, no matter how much I click on it.

Workaround: Close the line point editor and graphically add a bogus last point to the right of the last point you actually want.  Then return to the line editor, ignoring this last point. The position of what is now the next-to-last point can be edited without a problem. After editing, right-click on the bogus point to delete it.

**Comment by kunstmusik** [comment]
This is fixed and will be available in 2.6.0-test2 (and in the 2.6.0 final release).
