### ISSUE TITLE
knobs position in blue synth builder doesn't update after truncate

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#250]
To recreate: Create knob, with edit off set knob value to highest, with edit on edit max value to lower than current value, select truncate.  the value will change, but the knob position doesn't update.

**Comment by kunstmusik** [comment]
I believe knob related UI updates have been fixed due to replacing component with JavaFX-based design.  I will close out this issue.  If bad behavior appears again, please create a new issue. Thanks!
