### ISSUE TITLE
dropdown widget variables don't parse in i() statements

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#255]
In a mixer effect (and probably synth builder too, untested), you can not typecast a widget's variable straight into an i-rate var.  For example:
ivar = i(<var>)
does not work, instead you have to use an extra line as a workaround:
kvar = <var>
ivar = i(kvar)

**Comment by kunstmusik** [comment]
This issue was due to not updating parameters when the object name changed. I audited the code and moved things into the super class to ensure there is a consistent behavior between the objects. 

This fix will be in 2.6.0.  Thanks for reporting!
