### ISSUE TITLE
arrow keys on top/bottom line should move cursor to beginning/end

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#258]
When in a text editing window, if you're on the top line the up arrow should move the cursor to the beginning of the line, and likewise on the last line down arrow should move the cursor to the end of the line.

**Comment by kunstmusik** [comment]
I just checked a few text editors (vim, notepad, Atom) and none of these exhibit this kind of behavior.  I'm not sure I would like this myself, so will decline on this request.
