### ISSUE TITLE
allow render star/stop while editing effects

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#259]
Having to close and reopen the effect edit window while troubleshooting effect code is very disruptive to the workflow.  It would be great if we could start/stop rending either via the buttons or hotkey while the effect edit window remains open.

**Comment by kunstmusik** [comment]
This used to work but seems to have gotten lost somewhere.  I'll look at this for 2.6.0.

**Comment by kunstmusik** [comment]
This will be available in 2.6.0-test2 and later releases.
