### ISSUE TITLE
prompt for confirmation when deleting folders

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#272]
I think it would be a good idea to prompt the user for confirmation when deleting a folder out of any of the libraries (effect, instrument, code repository, etc).  If preferred, maybe only prompt if the folder contains multiple items?

**Comment by ainola** [comment]
This may or may not apply to your design paradigm but it's food for thought.

http://alistapart.com/article/neveruseawarning

**Comment by kunstmusik** [comment]
I've added a confirmation dialog as it was the simplest solution at this time.  It's not elegant, but it should suffice to help protect against accidental folder deletions.  Perhaps a better strategy of undoability would better serve users; if this becomes bothersome enough, we can address it in a future release.
