### ISSUE TITLE
allow removing of last layer in layer groups

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#275]
It would be useful to allow removing of the last layer in a layer group, which could go straight to "removing layer groups can not be undone" prompt

**Comment by tjingboem** [comment]
I think this can be closed as it has been implemented?
Now it is possible to Rightclick on the Layer and remove it

**Comment by kunstmusik** [comment]
Closing: I think it's better to prevent an empty layergroup. User can remove layer groups entirely if they want, and I'm not sure what one gets out of an empty layer group.  (Feel free to reopen if I'm missing something.)
