### ISSUE TITLE
any panel with editor, ctrl-f should focus editor and open search

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#284]
In any panel with an editor, ctrl-f should bring focus to the editor screen and open the find window regardless of current focus.  For example, in the orchestra tab, if you select an instrument and then immediately hit ctrl-f, focus should move to the editor window and open the search bar.

**Comment by kunstmusik** [comment]
I'm not sure I can implement this in a generic fashion to always delegate ctrl-f to search for editor sub-components. Also, if there are multiple editors, it's not clear which one gets the focus.  I'm going to pass on this one as I think there isn't enough gain compared to the time for implementing, vs. just using component tabbing or just selecting a text editor with a mouse.
