### ISSUE TITLE
seed for JMask

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#301]
a reply from Steven: For JMask, I think if I create a specific Random() object and pass it down when compiling, it should work.

my interest lies in having a seed factor in JMask. For backwards compatibility perhaps it is possible to do something like ?:
if no seed input at all
then
seed (0)

Older blue JMask files could continue to function i hope.

**Comment by tjingboem** [comment]
i have contacted André Bartetzki about the seed issue:

> Hello André,
> I understand very well that you do not support CMask anymore and i am not asking you to do anything, but i would really like to know:
> Is it in principle possible to add a global seed to the program?
> 

And his answer that may be helpful if implementing the seed:
>Hello Menno,
>in principle yes.
>The thing is, should it really be a global seed, that is a common seed for all fields and all their >randomly generated event parameters - or rather individual seeds per random generator? 
>A global seed should be easy to implement, as the random generators in CMask are indeed seeded >to the current number of clock ticks (C++ function clock () ).  
>Individual seeds are probably harder to implements as one have to implement individual random >generators - in CMask all events use the very same C++ generator by calling rand(). But I think, >individual seeds are more useful.
>
>However, there are three things that need to changed when a seed parameter is to be implemented:
>
>- a syntactical representation for the seed and the seeding number, that is something like "seed >1234", and a proper place for it in the textfile - probably at the beginning or after any text in {  } 
>
>- the parser:  it scans the text file for keywords like "mask" or "rnd", numbers and syntacting elements >like "( )", comments etc., and sets functions, options and parameters for the CMask processing >modules accordingly. 
>
>- the actual random number generator initialisation (in CMask done by a function called frandinit() )

**Comment by kunstmusik** [comment]
I added a seed field and a checkbox for the JMask Object.  If enabled, the seed value is used for a random number generator shared by all fields within the Jmask Object.  Otherwise, a random number generator seeded from system time will be used (same as previous behavior).  

This will be available for testing in 2.6.0-test2.
