### ISSUE TITLE
--env:RAWWAVE_PATH=/usr/local/share/csound/rawwaves/

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#303]
This entry works in Project Properties, but has no effect in Tools-->Options-->realtime Render

**Comment by kunstmusik** [comment]
I think this might be a misunderstanding of Tools->Options->Realtime Render.  The settings there set defaults for new projects. I tried setting this just now and then creating a new project and the value was set in the project's properties. 

If you want to set globally, you might want to use the Tools->".csoundrc editor". (Which reminds me, this should be updated for .csound6rc...)

I'll close those as not a bug.
