### ISSUE TITLE
/usr/local/lib

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#304]
With every new blue version i have to change the Java library because i build Csound myself - so it gets in /usr/local/lib and not in the set as default /usr/lib

please change blue file to look automatically for ${default_options} -J-Djava.library.path=/usr/lib/ \
as well as 
${default_options} -J-Djava.library.path=/usr/local/lib/ \

**Comment by kunstmusik** [comment]
This will be available in 2.6.0-test2. Thanks!
