### ISSUE TITLE
drag sound inside AudioClipObject

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#307]
1. i have an AudioClip on the AudioLayer
2. i shorten the Clip by either shrinking the right or from the left of the Clip
3. That means in the original sound in the AudioClip, there is some audio left or right but it does not show (because of this shrinking) and does not sound
4. Only the visible part of the AudioClip is played.

But...
5. i like to move the contents of the sound inside this shrunken sound a bit but NOT enlarge the Object (to look for the part of the sound inside the larger, not-shrunken sound), because there is some sound left in the beginning or end.

So, perhaps while holding a key i can drag the sound inside the Object - while maintaining the same size of the Object.

**Comment by kunstmusik** [comment]
Looking into this now; one thing I noticed in other programs, bars for audio files may have custom mouse handling when on the waveform, but simple move operations when on the label of the audio bar.  I may look at this kind of UI in the future, but for now, I will look to implement this using only a keyboard shortcut + mouse click/drag.

**Comment by kunstmusik** [comment]
I have implemented this using alt-click/drag, which seems to be the only open shortcut available as ctrl and shift are used.  This will be available in 2.6.0-test7 and the 2.6.0 final.  

(Sidenote: A rendering bug was found for the waveform while implementing this issue.  I am looking into this for test7 as well.)

Thanks for the request!

steven

**Comment by kunstmusik** [comment]
(FYI: The waveform file start time calculation for drawing was incorrectly calculated; now fixed, which results in the waveform properly drawing both when alt-dragging as well as when left-hand side resizing.)
