### ISSUE TITLE
ALSAsequencer Midi driver detection

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#309]
ALSAsequencer Midi driver detection and the in ports and out ports

**Comment by kunstmusik** [comment]
@tjingboem Could you assist further on this one?  The current code is reading from /proc/asound/seq/clients to find a list of clients to present for Midi input and output.  I'm running in a virtual machine and I'm not sure I have the same setup as you.

Could you note:

1.  What are the expected devices?
2. The output from running "cat /proc/asound/seq/clients"

I am deferring this to 2.6.1 so that I can get 2.6.0 out.

**Comment by tjingboem** [comment]
yes i can.
i put information in the manual: http://csound.github.io/docs/manual/RealTimeLinux.html
under "MIDI Input and Output (Midi Sequencer driver)"


My output of "cat /proc/asound/seq/clients":
Client info
  cur  clients : 6
  peak clients : 7
  max  clients : 192

Client   0 : "System" [Kernel]
  Port   0 : "Timer" (Rwe-)
  Port   1 : "Announce" (R-e-)
    Connecting To: 128:0
Client  14 : "Midi Through" [Kernel]
  Port   0 : "Midi Through Port-0" (RWe-)
    Connecting To: 128:0[r:0]
    Connected From: 128:0
Client  16 : "M Audio Delta 1010" [Kernel]
  Port   0 : "M Audio Delta 1010 MIDI" (RWeX)
    Connecting To: 128:0[r:0]
    Connected From: 128:0, 129:0
Client 128 : "jack_midi" [User]
  Port   0 : "port" (rw--)
    Connecting To: 14:0, 16:0, 130:0
    Connected From: 0:1, 14:0[r:0], 16:0[r:0], 129:0[r:0]
  Output pool :
    Pool size          : 500
    Cells in use       : 0
    Peak cells in use  : 0
    Alloc success      : 0
    Alloc failures     : 0
  Input pool :
    Pool size          : 200
    Cells in use       : 0
    Peak cells in use  : 6
    Alloc success      : 55
    Alloc failures     : 0
Client 129 : "Csound" [User]
  Port   0 : "Csound" (R-e-)
    Connecting To: 16:0, 128:0[r:0]
  Input pool :
    Pool size          : 200
    Cells in use       : 0
    Peak cells in use  : 0
    Alloc success      : 0
    Alloc failures     : 0
Client 130 : "Csound" [User]
  Port   0 : "Csound" (-We-)
    Connected From: 128:0
  Input pool :
    Pool size          : 200
    Cells in use       : 0
    Peak cells in use  : 1
    Alloc success      : 1
    Alloc failures     : 0

Here another output:
menno@muziek:~$ aconnect -i -o 
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 16: 'M Audio Delta 1010' [type=kernel]
    0 'M Audio Delta 1010 MIDI'
client 129: 'Csound' [type=user]
    0 'Csound          '
client 130: 'Csound' [type=user]
    0 'Csound   

In Claudia the 2 Csound Midi In and Out ports are called midi_capture6 and midi_playback6
![screenshot from 2016-07-29 21 01 53](https://cloud.githubusercontent.com/assets/6670911/17260427/99a4e802-55d0-11e6-88d7-32f8641aef7a.png)
This has to do with the fact that i am runningthe a2j bridge as well

**Comment by kunstmusik** [comment]
Is the issue that no devices are listed in Blue, or only some are? I see
that the code I have looked for "R" or "W" when searching for client
capabilities. However, I see that "jack midi" in your output shows "rw"
(lowercase).

**Comment by tjingboem** [comment]
For Midi drivers, i can choose from PortMidi, ALSA and null
There is no alsaseq driver available.
So i add " -+rtmidi=alsaseq -M16 -Q16" to the Advanced Settings in the Project Properties and get this output:

Render Command ( csound -+msg_color=false -+rtaudio=JACK -o dac:system:playback_ -i adc:system:capture_ -d -m1 --env:RAWWAVE_PATH=/usr/local/share/rawwaves -j4 -+rtmidi=alsaseq -M16 -Q16 /tmp/tempCsd4718586747303453033.csd )
UnifiedCSD:  /tmp/tempCsd4718586747303453033.csd
STARTING FILE
Creating orchestra
Creating score
rtaudio: JACK module enabled
sorting score ...
	... done
ALSASEQ: opened MIDI output sequencer
ALSASEQ: created output port 'Csound' 130:0
ALSASEQ: connected to 16:0
--Csound version 6.08 (double samples) Jul 12 2016
midi channel 1 using instr 1
midi channel 2 using instr 2
midi channel 3 using instr 1
midi channel 4 using instr 1
midi channel 5 using instr 1
midi channel 6 using instr 1
midi channel 7 using instr 1
midi channel 8 using instr 1
midi channel 9 using instr 1
midi channel 10 using instr 1
Multithread performance: insno:  -1  thread 1 of 4 starting.
Multithread performance: insno:  -1  thread 2 of 4 starting.
Multithread performance: insno:  -1  thread 0 of 4 starting.
midi channel 11 using instr 1
midi channel 12 using instr 1
midi channel 13 using instr 1
midi channel 14 using instr 1
midi channel 15 using instr 1
midi channel 16 using instr 1
displays suppressed
0dBFS level = 1.0
ALSASEQ: opened MIDI input sequencer
ALSASEQ: created input port 'Csound' 131:0
ALSASEQ: connected from 16:0
orch now loaded
audio buffered in 256 sample-frame blocks
reading 1024-byte blks of shorts from adc:system:capture_ (RAW)
system sr: 48000.000000
 0: adc:system:capture_ (system:capture_)
 1: adc:csound6:output (csound6:output)
 0: dac:system:playback_ (system:playback_)
 1: dac:csound6:input (csound6:input)
writing 512 sample blks of 64-bit floats to dac:system:playback_ 
SECTION 1:
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
0 errors in performance
0 512 sample blks of 64-bit floats written to dac:system:playback_


Because ALSASEQ is pretty new in Csound (only Raw Midi driver was available) and is superior to ALSA midi, i wondered if it could be detected and implemented in Blue. 

(Recently Jack Midi is added to Csound as well - i have only experimented briefly with it)

**Comment by kunstmusik** [comment]
AHhhhhhh I misread this ticket altogether.  Okay, let's take care of this in 2.6.1. :)

**Comment by kunstmusik** [comment]
I've added an 'alsaseq' option to the list of drivers and have the device ID's formatting to use "client:port" which looks to be the appropriate format for -Q and -M when using alsaseq.  This feature will be available in 2.6.1.
