### ISSUE TITLE
copy and paste knobs etc. between instruments

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#311]
i can copy code between instruments, but not the automation knobs, sliders etc. that go with the code.
Is this possible?

**Comment by kunstmusik** [comment]
Yes, in Edit mode, you can select multiple widgets, press rt-click and choose "copy" from the menu. Then in another BSB instrument, you can rt-click and choose paste.

**Comment by tjingboem** [comment]
i'm sorry that i have to get back to this, but it is still a problem to copy and paste the automation knobs, sliders etc on my system.
what i do:
- in BSB, i go to Edit Enabled
- select some knobs
- copy them (by rightclick, copy or just Control-C)
- got to my new insrument
- try to paste but the option is greyed out. And Control-V is empty

i'm using 2.6.0test4
Same goes with Control-X...they are all gone..

**Comment by tjingboem** [comment]
i'd like to add that text is copying and pasting fine

**Comment by tjingboem** [comment]
and i need to add that i am switching between projects too!

**Comment by kunstmusik** [comment]
The root cause of this was that some caching logic for editors was not working correctly.  I have fixed that which has fixed this issue.  The fix will be in the next build after 2.6.0-test4 (test5 or beta1, etc.)
