### ISSUE TITLE
not all automation parameters are shown

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#314]
I am building this crazy instrument with a lot of Automation options. In fact, too many, because i can not reach the all of them, as the picture shows: 
![screenshot from 2015-06-26 14 03 42](https://cloud.githubusercontent.com/assets/6670911/8379308/66a7f638-1c1f-11e5-8770-157a3e053d85.png)

Is there a way to get to the automation parameters that are not shown??

**Comment by kunstmusik** [comment]
fixed in develop branch, will be available in next release after 2.6.0-test4 (assuming test5)
