### ISSUE TITLE
score tab is not graphically always updated

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#315]
Not always, but sometimes: after having created knobs or sliders, and having drawn some corresponding automation lines in the Score Tab, and then after having removed these very same knobs or sliders, their entries remain in the automation menu.

Perhaps related: sometimes i can not select an Object when coming from the Orchestra Tab. After a few times switching and clicking in these Tabs, ans switching a few times from Single Line to Score, i am finally able to select an Object and all goes well from that point on. 
Until an hour later, the same thing happens all over again.
It seems pretty random to me.

My guess is that somehow all the elements in the Score Tab are not graphically updated - so that i can not select them. This goes for the Objects, but also for the automation menu entries

**Comment by kunstmusik** [comment]
Closing as this looks to be resolved now.
