### ISSUE TITLE
File Selector in BSB

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#317]
The File Selector in the BSB refuses to accept new file entries. The new file is shown in the BSB screen, but the old one appears in the generated code.

**Comment by kunstmusik** [comment]
Hi Menno,

I just tried this here and it is working, at least with the latest from the develop branch (tested on Xubuntu 14.04).  Is the issue you found using 2.6.0_test4 or a 2.5.14? 

Thanks!
steven

**Comment by tjingboem** [comment]
sometimes it works, sometimes it doesn't. 
For me this issue has been there for years. Also, it does not remember the home dir,  soemtimes, so when i enter a file from /home/menno/xxx, a next time i open blue i only see xxx. Most of the time i select the file again to get the complete path in and it will run for a while - until it is not recognized...
I did not discover a pattern in its mis-behaviour yet

i am using test4 version all the time - the best way to catch the bugs if any ;)

**Comment by tjingboem** [comment]
My instrument ImagePlayer v2 has this File Selector. You can find it in BlueShare.
I am not able to use the file selector but just put the image's entry path in the code instead.


This is the error message i get if i use the file selector:

INIT ERROR in instr 1: imageload: cannot open image gS_blue_str0.
image	imageload	"gS_blue_str0"	
INIT ERROR in instr 1: imageload: cannot open image gS_blue_str0.
image	imageload	"gS_blue_str0"	
ftable 2:
ftable 3:
	  B  0.312 - note deleted.  i1 had 2 init errors

this issue tracker does not allow me to attach the blue file nor text...

**Comment by kunstmusik** [comment]
I think there may be issues if you move the project file around; is that the case?  

For imageload, it looks like you have "stringChannelEnabled" set on the file selector.  For that, you should not use quotes within your code.

**Comment by tjingboem** [comment]
solved.
I changed the code to: image imageload <file>  
and "stringChannelEnabled" adds the ¨ ¨. Is logic once you know it :)

i will close this issue if you don't mind
and thank you for your help
