### ISSUE TITLE
add new UDO repositories

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#319]
like yours and Joachims

**Comment by kunstmusik** [comment]
I had just thought about this yesterday.  It would require some way to interrogate a github site for UDOs.  I think this would not be a problem though, but I'll have to talk to Joachim and perhaps the Csound mailing list to get a consensus on a repository format. After that, I can build some tooling that could pull from various repositories.

**Comment by tjingboem** [comment]
i have made some UDOs available on a personal page today - not a github site. They may be simple UDOs but i think they make musical sense. I'm also in the process of producing simple example csds.

I'm always using the extension .udo. Could it possible and a good idea to import UDOs from whatever site - as long as the extension of the file = .udo?

**Comment by kunstmusik** [comment]
I had a similar issue to this a couple weeks ago but forgot to look into this.  The old code the worked with the UDO database (now defunct) did some opcode parsing from files, but I think it assumed one UDO per file.  That should serve as a basis for reading UDO definitions from a file.

I think the larger ticket idea is what you are saying, to be able to add Github repositories as UDO sources and allow importing from them.  However, I don't know if it is good to just use .udo, as it might require a lot of work to process an entire github repo and look through.  I think it might require looking through other .udo files too if one .udo #includes andother .udo file. 

One thing though that should be added is the ability to import/export to files.  That would be useful on its own and the code for that would likely be re-used in implementing a larger repository-based import system.

**Comment by kunstmusik** [comment]
Closing: import/export works, github option is not simple and we may be addressing it csound community-wide via csound package manager.
