### ISSUE TITLE
more Automation Points options

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#322]
for moving about the Automation Points in Single Line Mode, for example:
- use Ctrl + click to create AP that stays on exactly the same X axis. Then: the first movement up or sideways will stay on the same X or Y axis. 
What happens now is that when you set a AP between other APs, this new AP is created somewhere on that spot 
- use Shift + select to select several APs so that all the selected APs can be moved around a bit

**Comment by kunstmusik** [comment]
I have implemented the ctrl-drag option that limits editing to a single direction.  The use of ctrl can be used after dragging starts as well.  

I found that shift-selection of points is already supported for automation editing in single-line mode (via marquee).

These changes will be available in 2.6.1_test3.
