### ISSUE TITLE
2.6 not fully functional.

### ISSUE THREAD

**Issue by kmkrebs** [kunstmusik/blue#329]
Hi -- I installed Blue **2.6** yesterday on my machine, running Fedora 24, and I seem to have encountered some kind of problem.  I get the main Blue window, but I can't open or create a new project, and most of the menus don't have any options listed in them.

I still have **2.5.14** installed, and it works with no problems at all.

I was able to access the "Blue Application Log" from the view window. It's 500+ lines, so instead of posting it in this message, here's a link to it: https://dl.dropboxusercontent.com/u/118844/blue_app_log.txt

Help!

**Comment by kunstmusik** [comment]
It looks like you are using OpenJDK but do not have JavaFXinstalled. I think some systems distributions package it separately from the base OpenJDK. Please try finding a package for JavaFX or instilling OracleJDK and let me know if there are further issues.

**Comment by kmkrebs** [comment]
Thanks for the info.. unfortunately setting up OracleJDK as an alternative on Fedora is not as easy as I expected!

**Comment by kunstmusik** [comment]
You might try the information here:

https://ask.fedoraproject.org/en/question/59412/sticky-how-do-i-install-oracle-java/

**Comment by kmkrebs** [comment]
Thanks Steven -- than was much clearer and simple than the previous instructions I found.  I followed them and 2.6 is working like a charm.
