### ISSUE TITLE
Scanned Matrix in Blue

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#332]
- cannot create or load a matrix

When trying to create the Scanned Matrix window crashes, when trying to load the matrices are not seen.

**Comment by kunstmusik** [comment]
A quick test here and the matrix window opened and operated just fine (Win
10).  I will try on Linux today.  Question: are you using OpenJDK or Oracle
JDK?

**Comment by kunstmusik** [comment]
I tested on Debian 64-bit, Oracle Java 1.8.0_101. I was able to both create as well as load matrices.

**Comment by tjingboem** [comment]
i was able to create a new empty matrix but could not load an existing one, because the file circularstring-128 did not show. I do have this file in that place, as you can see in the screenshot.
![screenshot from 2016-08-25 19 28 18](https://cloud.githubusercontent.com/assets/6670911/17979468/09a1fdd6-6afb-11e6-86f7-c73ec4713736.png)

**Comment by kunstmusik** [comment]
Could you email me a zip of the different matrices?  I opened string-128 and it opened just fine here.  Maybe there'll be a different outcome with a different file.

**Comment by kunstmusik** [comment]
Thanks for sending those files.  I can reproduce the issue now on Linux and see that it is a file manager problem and not necessary a scanned matrix one.  Looking into it now.

**Comment by kunstmusik** [comment]
Fixed, this will be available in 2.6.1.
