### ISSUE TITLE
extensions for ObjectBuilder

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#348]
- automation line option
- a Comment Tab ( so it can be released in BlueShare or otherwise)

**Comment by kunstmusik** [comment]
I'm pretty sure this ticket was for the Sound SoundObject and not ObjectBuilder. I will work on this for Sound, and do another analysis of merging ObjectBuilder and Sound.

**Comment by kunstmusik** [comment]
@tjingboem I'm working on the automation the past few days and it's been tricky.  However, what I'm wondering about now is the request for a comment field.  Do you think this should be for all SoundObjects or just Sound and ObjectBuilder?  I suppose most other objects aren't really as useful for sharing and, even if shared, they have places to put comments within code.  On the other hand, I can add a comment field to all objects and add it to the SoundObjectProperties window as another possibility.  I was going back and forth on it but I think for now I'm leaning just slightly towards just Sound and ObjectBuilder.

**Comment by tjingboem** [comment]
I wanted, at one point, share some SoundObjects, because they can be used almost like instruments - self-contained and are worth being shared. I have an example here:
![screenshot from 2017-08-17 12-59-41](https://user-images.githubusercontent.com/6670911/29409387-3db570ca-834c-11e7-9307-15748c1681f3.png)

Here i activate or deactivate the JackTransport opcode so i can control the movements of a second computer

As i remember correctly, i was using different SoundObjects of the same "instrument" but with slightly different settings. On the Timeline, they would act like "program changes" of the Midi world. A commetn tab would be welcome there: for personal comments, also for sharing in a BlueShare that accepts SoundObjects as Instruments With Score.

**Comment by tjingboem** [comment]
a bit confusing: i am talking all along about the Sound SoundObject :), and the ObjectBuilder too.

I have a screenshot that shows an example of how - like the Sound SoundObject - have become a selfcontained entity. 
![screenshot from 2017-08-17 21-00-33](https://user-images.githubusercontent.com/6670911/29429000-693e5598-838f-11e7-9a1c-d1036abfdffe.png)

This is an attempt to make the AthenaCL score generator as user-friendly as i can make it :)
(JMask is doing a better job at it, but hey - i'm trying!)

I would like to share this AthenaCL score instrument in BlueShare IF possible. A while ago i wrote an article about the subject: https://github.com/kunstmusik/blue/wiki/Blue's-athenaCL
A comment tab would allow a detailed explanation on its usage and confirm its selfcontainmentness.

A part of this feature request has been made in:
export SoundObject to BlueShare #358
so they overlap i think.

**Comment by kunstmusik** [comment]
Sounds like we are on the same page then to limit this to Sound and ObjectBuilder.  I will take the approach to apply this only to those objects for now, and I think if it becomes desirable to have comments be a part of all SoundObjects, it would be easy to reuse this work easily.  I will proceed with this for Sound and ObjectBuilder now, thanks for the feedback!
