### ISSUE TITLE
Update BSB Groups

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#353]
Tracking changes to implement for BSB Groups before 2.7.0 release (implemented in #312).  So far:

* Allow color selection for background, title
* Provide sizing options beyond the automatic sizing that currently exists

**Comment by tjingboem** [comment]
the Group window has a black title bar, where one can enter text - or no text at all.
- can there be an option to NOT generate the titlebar? In this case, just a rectangle will be created, where i could make use of the font possibilities when i want to give the Group a title.

**Comment by tjingboem** [comment]
i am missing the Undo function...when i accidentally throw something away or move something to a place that turns out to be not so great, i would like to use Ctr + z to Undo these movements.

**Comment by kunstmusik** [comment]
* I have added background color changing, title color changing, and ability to enable/disable the titlebar. (http://www.kunstmusik.com/blue_2.7.0_dev.zip now has the latest changes.)
* I have added issue #359 to handle undoability: this will take time to implement and I think I will do this for 2.7.1, so that 2.7.0 can go out sooner.
* I have added issue #360 to deal with better BSBGroup width/height options, but also to have visual editing of BSBWidgets' widths/heights via drag handles.  That is a bigger enhancement that should be doable this release. 

I will close this issue as all issues have been addressed or added to new items. For new features/enhancements, please file new issues.
