### ISSUE TITLE
Cannot build without csound-manual unless I manually create release dir

### ISSUE THREAD

**Issue by fcahoon** [kunstmusik/blue#356]
When I try to build blue using "Clean and Build Project" in NetBeans 8.2, I get the following error:

/home/forrest/src/blue-upstream/blue/csound-manual/build.xml:34: /home/forrest/src/blue-upstream/blue/csound-manual/release does not exist.

When I create the release dir under csound-manual and re-build, the build succeeds.

**Comment by kunstmusik** [comment]
@fcahoon Thanks for mentioning this. I've put in a small fix to the build.xml file that should take care of this problem.
