### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by carlgueck** [kunstmusik/blue#372]
Please note that for installation on Linux, the documentation fails to mention that `javafx` is required. Simply adding this would save 15 minutes of googling why the install was broken.

Linux does not package JavaFX with the OpenJDK generally installed by the package manager.

Bugfix: `sudo apt install openjfx`

**Comment by kunstmusik** [comment]
It's mentioned in the manual on this page:

http://blue.kunstmusik.com/manual/html/requirements.html
I'm going to be adding some more step-by-step information for the next
release.
