### ISSUE TITLE
dropdownmenu strings option

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#373]
it now produces values, but would it be possible to let it produce strings as well?

**Comment by kunstmusik** [comment]
@tjingboem - I did some work on this and ran into an issue. The problem I found is what to do about automation. I see two options:

1. If String Channel is enabled, I could disallow automation
2. Update automation system to allow setting different strings values at runtime.  Could possibly be done by still using the index value during automation but using a String array in Csound code to map the index to a String value.   

BTW: Just to double-check, as I realized maybe I may have over thought this issue.  Currently, if you turn automation off for dropdowns, a static string value is generated for the <object_id>.  Is what you are requesting here to have the ability to change strings are runtime (via string channel, similar to how BSBFileSelector can change values while a project is running)?

**Comment by tjingboem** [comment]
I'll explain my motivation for this request:
If i remember well, this request was made because i was trying to get a decent way to make a GUI for nGen, using the ObjectBuilder. 
![ngenobject](https://user-images.githubusercontent.com/6670911/34008810-d935dd1a-e106-11e7-83d9-4be3c8cc5d0c.png)

There are several input filters like "no" for note input and dozen others.
When i have a dropdown list where i can choose "no" or "op" or whatever options there are in nGen, this "no" should be placed at the right spot in the score.

nGen needs for example p5 dv(0) no se(10 .9 [c4, cs3, fs4, g5] .1 [gf2/bfff2])
The place where "no" is could have an empty space "  " when not needed.

Come to think of it, i now see that it needs something to get replaced, something like "{empty string}" and that this would be another Blue variable like the 
;[once]{ 
blah
;}
command.
Blue, when rendering, should ignore this "{empty string}"
So, no need for automation in this case - only pure replacement of an empty space in the score.

Perhaps my idea is not that good or practical...it is more complicated than meets my eye :)

**Comment by tjingboem** [comment]
i found, by looking at an existing effect, that it is already possible to replace text using the dropdownmenu. My confusion had to do with the fact that the behavior of the Dropdown Menu is very different when it is in 'AutomamationAllowed' mode or not. Text will actually be replaced when this mode is set to off.
This is fine for what i want, so i will close the issue. I will open another because i would like to be able to get "   " (empty space) when using the Dropdownmenu.
