### ISSUE TITLE
Can't find Java 1.8 but 1.8 is installed

### ISSUE THREAD

**Issue by dza6549** [kunstmusik/blue#379]
Hi

I have tried running blue64.exe but I get an error message saying blue needs Java 1.8 or higher. In the screenshot below you can see that I have Java 1.8.0_144 installed.

What should I try next please?

Thanks

![csound-blue](https://user-images.githubusercontent.com/27390320/32986452-d4b02d4e-cd25-11e7-8c3e-6b1bfa76e32c.png)

**Comment by kunstmusik** [comment]
It looks to me that you have the 32-bit Java Virtual Machine (on my system,
java -version shows:

"C:\Users\stevenyi\work\csound\study\csd>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)"

blue64.exe will need the 64-bit Java virtual machine.

You might double check that you installed 64-bit (x64) version of Java and
not the 32-bit (i586) version.

**Comment by dza6549** [comment]
OK thanks kunstmusik.
