### ISSUE TITLE
remains white after Freeze

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#382]
after freezing an Object, screen remains white. After clicking on the screen parts of it become visible and everything runs normal afterwards

![screenshot from 2017-12-19 12-58-07](https://user-images.githubusercontent.com/6670911/34156773-f390d4d8-e4be-11e7-901e-ac5b6ca0926b.png)
![screenshot from 2017-12-19 12-57-30](https://user-images.githubusercontent.com/6670911/34156774-f52964ea-e4be-11e7-8bb1-fda50f0907c9.png)

**Comment by tjingboem** [comment]
i've tried to find this file again and tried dozens of them. I did not find it. 
All of these checked files all have to do with the construction of the nGen score generator and perhaps may have to do with the solved issue empty space with Dropdown Menu #383??
I may have been working with a file that was already corrupted...

I suggest, as me too i cannot replicate this issue any more, to close this issue. Next time i'll give all the info i have - sorry for this one.

**Comment by kunstmusik** [comment]
No worries, the screenshot definitely shows there was a problem at some point.  Let's just monitor the situation and if it happens again maybe we will have better information to diagnose.  Closing for now, thanks!

**Comment by tjingboem** [comment]
[white.blue.txt](https://github.com/kunstmusik/blue/files/1650064/white.blue.txt)

i have some additional evidence :)
With the blue file above, quite heavy on CPU, so i had to Freeze the Object before being able to hear it.
![screenshot from 2018-01-21 19-50-06](https://user-images.githubusercontent.com/6670911/35197781-2bc04c86-fee5-11e7-9d42-feb417895c94.png)

and after clicking on some menu the screen looks like this:
![screenshot from 2018-01-21 19-50-33](https://user-images.githubusercontent.com/6670911/35197793-4160efe6-fee5-11e7-8112-b83f4147110d.png)

i hope this time you are able to get this bug.
