### ISSUE TITLE
No sound through BlueMixer

### ISSUE THREAD

**Issue by jondf** [kunstmusik/blue#384]
There's no sound when I try to use blueMixerOut; using outc (or disabling the BlueMixer) works though.

I'm running Blue 2.7.3 on Fedora 26 with OpenJDK 1.8.0.

Hopefully it's something simple; here's an example of realtime .CSD output using BlueMixer:

##############

;
; "Mixer Test"
; by Steven Yi
;
; Test file for blue's Mixer system.  Try rendering with loop on and experimenting with
; the fader values in the mixer dialog.
;
; Generated by blue 2.7.3 (http://blue.kunstmusik.com)
;

<CsoundSynthesizer>

<CsInstruments>
sr=48000
ksmps=16
nchnls=2

ga_bluemix_0_0	init	0
ga_bluemix_0_1	init	0
ga_bluemix_1_0	init	0
ga_bluemix_1_1	init	0
ga_bluesub_SubChannel1_0	init	0
ga_bluesub_SubChannel1_1	init	0
ga_bluesub_SubChannel2_0	init	0
ga_bluesub_SubChannel2_1	init	0
ga_bluesub_Master_0	init	0
ga_bluesub_Master_1	init	0

gk_blue_auto0 init 0
gk_blue_auto0 chnexport "gk_blue_auto0", 3
gk_blue_auto1 init 0
gk_blue_auto1 chnexport "gk_blue_auto1", 3
gk_blue_auto2 init 0
gk_blue_auto2 chnexport "gk_blue_auto2", 3
gk_blue_auto3 init 0
gk_blue_auto3 chnexport "gk_blue_auto3", 3
gk_blue_auto4 init 0
gk_blue_auto4 chnexport "gk_blue_auto4", 3

gi_square		ftgen 0, 0, 65537, 10, 1, 0, 0.111111, 0, 0.4, 0, .020408163, 0, .012345679, 0, .008264463

gi_sine	ftgen 0, 0, 65537, 10, 1

	opcode yiEnvelope,k,ioooooo

ienvType, iattack, idecay, isus, irel, iOldAmp, iNewAmp	xin

itie	tival
idur = p3

iEndAmp = iNewAmp / iOldAmp

if (ienvType == 0) then
	kenv	adsr	iattack, idecay, isus, irel
elseif (ienvType == 1) then	
	kenv 	linseg	0, p3 * .5, 1, p3 * .5, 0

elseif (ienvType == 2) then	
	kenv	linseg 	0, p3 - .1, 1, .1, 0	

elseif (ienvType == 3) then

    if (itie == 0 && p3 < 0) then
        ; this is an initial note within a group of tied notes
        kenv	linseg	0, .2, 1,  .2, 1
       
    elseif (p3 > 0 && itie == 1) then
        ; this is an end note out of a group of tied notes
        kenv linseg	1, p3 - 1, 1, 1, 0
 
    elseif (p3 > 0 && itie == 0) then
        ; this is a stand alone note
        kenv adsr iattack, idecay, isus, irel
    else
        ; this is a middle note within a group of tied notes (p3 < 0 && itie == 1)
        kenv line 1, abs(p3), iEndAmp
    endif  

endif

	xout 	kenv

	endop
	opcode getFrequency,i,i

ipch 	xin

iout	= (ipch < 15 ? cpspch(ipch) : ipch)
	
	xout	iout

	endop
	opcode blueEffect0,aa,aa ; ReverbSC

ain1,ain2	xin
aout1, aout2  reverbsc ain1, ain2, 0.85, 8000.0

aout1 = (ain1 * 0.3) + (aout1 * (1 - 0.3))
aout2 = (ain2 * 0.3) + (aout2 * (1 - 0.3))

xout	aout1,aout2

	endop

	instr 1	;triangle
ipch 	getFrequency p4
ipch2 	getFrequency p5

kpchline 	line ipch, p3, ipch2

;print ipch, ipch2

iamp 	= ampdb(p6)
iSpace	= p7
ienvType	= p8

itable	= gi_square

kenv	yiEnvelope ienvType, .1, .05, .95, .1

;aout	oscili iamp * kenv, kpchline, itable
;aout	vco 	iamp * kenv, ipch, 3, .5

aout	vco2	1, kpchline, 12
aout2	vco2	1, kpchline + .0009, 12
aout3	vco2	1, kpchline + .0007, 12

aout	sum aout, aout2, aout3
aout	= aout * .333

kCut	= (kpchline * 4 * kenv) + kpchline

kCut    	limit kCut, sr * 0.0002, sr * 0.48

;if kCut < 20000 kgoto kCutPass
;  kCut = 20000
;kCutPass:
;printk2 kCut

aout 	butterlp aout, kCut

aout	= aout * iamp * kenv

iSpace	= iSpace * 3.14159265359 * .5
krtl     	= sqrt(2) / 2 * (cos(iSpace) + sin(iSpace)) ; CONSTANT POWER PANNING
krtr     	= sqrt(2) / 2 * (cos(iSpace) - sin(iSpace)) ; FROM C.ROADS "CM TUTORIAL" pp460

aLeft 	=	aout * krtl
aRight	=	aout * krtr

;	outs aLeft, aRight

ga_bluemix_0_0 +=  aLeft
ga_bluemix_0_1 +=  aRight

	endin

	instr 2	;simple fm 2:1
ipch 	= p4
ipch2	= p5

ipch 	= (ipch < 15 ? cpspch(ipch) : ipch)
ipch2 	= (ipch2 < 15 ? cpspch(ipch2) : ipch2)

kpchline 	line ipch, p3, ipch2

iamp 	= ampdb(p6)
iSpace	= p7
ienvType	= p8

kenv	yiEnvelope ienvType

; SOUND GENERATION CODE

icar	= 2
imod	= 1

aout	foscili  	iamp * kenv, kpchline, icar, imod, kenv, gi_sine

iSpace	= iSpace * 3.14159265359 * .5
krtl     	= sqrt(2) / 2 * (cos(iSpace) + sin(iSpace)) ; CONSTANT POWER PANNING
krtr     	= sqrt(2) / 2 * (cos(iSpace) - sin(iSpace)) ; FROM C.ROADS "CM TUTORIAL" pp460

aLeft 	=	aout * krtl
aRight	=	aout * krtr

ga_bluemix_1_0 +=  aLeft
ga_bluemix_1_1 +=  aRight

	endin

	instr BlueMixer	;Blue Mixer Instrument
ktempdb = ampdb(gk_blue_auto1)
ga_bluemix_1_0 *= ktempdb
ga_bluemix_1_1 *= ktempdb
ga_bluesub_SubChannel1_0	+=	ga_bluemix_1_0
ga_bluesub_SubChannel1_1	+=	ga_bluemix_1_1
ktempdb = ampdb(gk_blue_auto0)
ga_bluemix_0_0 *= ktempdb
ga_bluemix_0_1 *= ktempdb
ga_bluesub_SubChannel2_0	+=	ga_bluemix_0_0
ga_bluesub_SubChannel2_1	+=	ga_bluemix_0_1
ktempdb = ampdb(gk_blue_auto2)
ga_bluesub_SubChannel1_0 *= ktempdb
ga_bluesub_SubChannel1_1 *= ktempdb
ga_bluesub_SubChannel2_0	+=	ga_bluesub_SubChannel1_0
ga_bluesub_SubChannel2_1	+=	ga_bluesub_SubChannel1_1
ktempdb = ampdb(gk_blue_auto3)
ga_bluesub_SubChannel2_0 *= ktempdb
ga_bluesub_SubChannel2_1 *= ktempdb
ga_bluesub_Master_0	+=	ga_bluesub_SubChannel2_0
ga_bluesub_Master_1	+=	ga_bluesub_SubChannel2_1
ga_bluesub_Master_0, ga_bluesub_Master_1	blueEffect0	ga_bluesub_Master_0, ga_bluesub_Master_1
ktempdb = ampdb(gk_blue_auto4)
ga_bluesub_Master_0 *= ktempdb
ga_bluesub_Master_1 *= ktempdb
outc ga_bluesub_Master_0, ga_bluesub_Master_1
ga_bluemix_0_0 = 0
ga_bluemix_0_1 = 0
ga_bluemix_1_0 = 0
ga_bluemix_1_1 = 0
ga_bluesub_SubChannel1_0 = 0
ga_bluesub_SubChannel1_1 = 0
ga_bluesub_SubChannel2_0 = 0
ga_bluesub_SubChannel2_1 = 0
ga_bluesub_Master_0 = 0
ga_bluesub_Master_1 = 0

	endin

</CsInstruments>

<CsScore>

i1	0.0	2	8.00	8.00	80	0	1
i2	0.0	2	9.00	8.00	80	0	1
i"BlueMixer"	0	4	
e

</CsScore>

</CsoundSynthesizer>

############

Thanks,

Jon

**Comment by kunstmusik** [comment]
@jondf - I tested here on Win10 using blue/examples/features/mixer.blue and it ran alright for me.  Some things to check:

1. What version of Csound are you using?  
2. In Blue, could you double-check that you are using the "Csound 6 API" renderer? This option shows up under the "Tools->Option" menu, in the Blue->Realtime Render tab. 
3. If you use the mixer.blue file, turn off looping and press the play button.  Open up the "Output" window from the Window menu.  You should see output like:

```
Render Command ( csound -+msg_color=false -+rtaudio=PortAudio -o dac -d -m135 C:\Users\stevenyi\work\nbprojects\blue\examples\features\tempCsd1309502824185287985.csd --env:SFDIR=C:\Users\stevenyi\work\nbprojects\blue\examples\features )
WARNING: could not open library 'c:\Users\stevenyi\work\csound\csound\msvc\csound-vs\RelWithDebInfo\fluidOpcodes.dll' (-1)
WARNING: could not open library 'c:\Users\stevenyi\work\csound\csound\msvc\csound-vs\RelWithDebInfo\libfluidsynth.dll' (-1)
UnifiedCSD:  C:\Users\stevenyi\work\nbprojects\blue\examples\features\tempCsd1309502824185287985.csd
STARTING FILE
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled
instr BlueMixer uses instrument number 3
Elapsed time at end of orchestra compile: real: 0.090s, CPU: 0.090s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.090s, CPU: 0.090s
displays suppressed
0dBFS level = 32768.0
ftable 101:
ftable 102:
orch now loaded
audio buffered in 4096 sample-frame blocks
PortAudio V19.6.0-devel, revision unknown
   0: dac0 (Microsoft Sound Mapper - Output [MME])
   1: dac1 (Speakers (Realtek High Definiti [MME])
   2: dac2 (ASIO4ALL v2 [ASIO])
   3: dac3 (Speakers (Realtek High Definition Audio(SST)) [Windows WASAPI])
   4: dac4 (Speakers 1 (Realtek HD Audio output with SST) [Windows WDM-KS])
   5: dac5 (Speakers 2 (Realtek HD Audio output with SST) [Windows WDM-KS])
   6: dac6 (Headphones 1 (Realtek HD Audio 2nd output with SST) [Windows W)
   7: dac7 (Headphones 2 (Realtek HD Audio 2nd output with SST) [Windows W)
PortAudio: selected output device 'Speakers (Realtek High Definiti'
writing 8192 sample blks of 64-bit floats to dac 
SECTION 1:
new alloc for instr 1:
WARNING: Division by zero
new alloc for instr 2:
WARNING: Division by zero
new alloc for instr BlueMixer:
B  0.000 ..  2.000 T  2.000 TT  2.000 M:  15656.2  17733.0
B  2.000 ..  4.000 T  4.000 TT  4.000 M:   4206.3   4139.1
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  15656.2  17733.0
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 4.196s, CPU: 4.196s
closing device
47 8192 sample blks of 64-bit floats written to dac
```

Could you paste what you get?

**Comment by jondf** [comment]
Hi, thanks for the help; I have it set to "Csound 6 API" for rendering in the Realtime Render tab. When I run "csound" in the terminal I get "Csound version 6.03.2 (double samples) Feb 10 2017"; I assume this is same that Blue is using? Also, I have this same mixer problem with any Blue project.

Here's the output from "mixer.blue":

Render Command ( csound -+msg_color=false -+rtaudio=ALSA -o dac -b512 -B2048 -d -m135 /home/jfetsch/blue/examples/features/tempCsd3343672747548035506.csd --env:SFDIR=/home/jfetsch/blue/examples/features )
UnifiedCSD:  /home/jfetsch/blue/examples/features/tempCsd3343672747548035506.csd
STARTING FILE
Creating orchestra
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
instr BlueMixer uses instrument number 3
Elapsed time at end of orchestra compile: real: 0.005s, CPU: 0.006s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.005s, CPU: 0.007s
--Csound version 6.03.2 (double samples) Feb 10 2017
displays suppressed
0dBFS level = 32768.0
ftable 101:
ftable 102:
orch now loaded
audio buffered in 512 sample-frame blocks
ALSA output: total buffer size: 2048, period size: 512 
writing 1024 sample blks of 64-bit floats to dac 
SECTION 1:
	  B  0.000 - note deleted. instr -2147483648(200) undefined
new alloc for instr 1:
WARNING: Division by zero
new alloc for instr 2:
WARNING: Division by zero
B  0.000 ..  2.000 T  2.000 TT  2.000 M:      0.0      0.0
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0      0.0
	   overall samples out of range:        0        0
1 errors in performance
Elapsed time at end of performance: real: 1.976s, CPU: 0.393s
188 1024 sample blks of 64-bit floats written to dac

**Comment by kunstmusik** [comment]
Blue uses the version of Csound installed on the system, which in your case looks to be from Fedora's repository.  The one line that is suspicious from your output is:

```
 B 0.000 - note deleted. instr -2147483648(200) undefined
```

Csound 6.03.2 is pretty old (from 2014; I've filed an issue for Csound to see about getting packages updated for Linux distros: https://github.com/csound/csound/issues/907).  I suspect that Blue is using more of the API than it did in 2014 and that there's a problem in 6.03.2 that may have been fixed since then. (Namely, the odd instr number seems like a bad interpretation of strings, and I recently made the BlueMixer use a named instrument to address another issue I found.)

The best, but most complex, option would be to uninstall Csound and related packages, then build and install Csound using the latest sources.  Let me know if you're comfortable with that or not; if not, I can see about other solutions.

**Comment by jondf** [comment]
Are there any configurations in Blue that I could change to avoid the (possible) bad string?

**Comment by kunstmusik** [comment]
There aren't any configuration options and really the problem looks to be with that that version of Csound. (i.e., Blue is generated good values, but Csound 6.03.2 does not work as it should.) I also don't think it makes sense for me to go through the effort to put in a config option into Blue to workaround a bug in an older version of Csound that's since been fixed.  

If you're not comfortable building Csound, then some things you could try:

1. Use an older version of Blue (2.7.2 or earlier).  These versions generates the Mixer instrument using a numbered instrument. If that works, then that version of Csound may be susceptible to bugs using named instruments.  

2. Wait until a new RPM for Csound can be made.  It looks to me that other csound devs are starting to reach out to package maintainers to see what can be done for that.

**Comment by jondf** [comment]
I'll try 2.7.2; if it's just the string causing the problem I think that will work, thanks.

**Comment by jondf** [comment]
I installed 2.7.2 and the mixer works well, thanks.
