### ISSUE TITLE
subchannel error

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#386]
-the main signal get divided (crossover filter) into 3 filtersections: low, mid, high
-then send to 3 Subgroups (see blue file)
-a new subchannels is created to send the 3  subgroups to so i have them under 1 fader
- i try to rename the last subchannel but that is impossible.
![screenshot from 2018-01-09 12-06-06](https://user-images.githubusercontent.com/6670911/34718043-81a8a7b0-f535-11e7-843f-c35a8c307bb2.png)

[cross2.blue.txt](https://github.com/kunstmusik/blue/files/1614838/cross2.blue.txt)
![screenshot from 2018-01-09 11-59-08](https://user-images.githubusercontent.com/6670911/34717883-e045f67a-f534-11e7-93d0-aebb85094658.png)

**Comment by kunstmusik** [comment]
I wasn't able to reproduce this directly, but I could see in the code a way that this error could happen. I put in some changes that should hopefully prevent the error. (Uploaded a build to http://kunstmusik.com/blue_2.7.4_dev.zip).
