### ISSUE TITLE
pinpointing the point in AL

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#388]
a point on the AL can be created and with Ctrl can be moved up/down or right/left, depending whatever direction you start moving. This works fine.

when i click, with Ctrl, to create a point on the AL, this point is likely to bend the total AL a bit because it is hard to  point with the mouse on the AL exactly. Certainly when the AL represents for example the frequency, the frequency change has a great impact and is sometimes hard or impossible to get it back to the original position on the line before the point was created.

here is a demonstration film to show you what i mean  -i had to append .txt to it in order to be accepted in this issue: 
[point-2018-01-14_11.22.35.mp4.txt](https://github.com/kunstmusik/blue/files/1629234/point-2018-01-14_11.22.35.mp4.txt)

What i propose is that when you click, with Ctrl, on the AL, then this created point starts to exist on the ALs' line exactly, and not a bit higher or lower. Then, the direction you move the point to (up/down or right/left), will be the movement (still with Ctrl) that the user chooses.

**Comment by kunstmusik** [comment]
I will implement using alt instead of ctrl since ctrl-click has become used now for pasting copied automations.
