### ISSUE TITLE
scanned matrices do not show

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#389]
the filter "All Files" do not show the matricies that are in the folder. I see only ".DS_Store"

**Comment by tjingboem** [comment]
but they show when i rename the matricies and give them the extension ".matrix"

**Comment by tjingboem** [comment]
...which is ok but can the need of this extension .matrix be noted in the manual?

**Comment by kunstmusik** [comment]
Could you mention where this is?  I tried the Scanned Synthesis Matrix Editor to load a file and it had the "All Files" filter and I could see different files including with .matrix and without.  (This problem may not show up on Windows, or I may be opening matrix files from a different part of program than you.)

**Comment by tjingboem** [comment]
i do not exactly understand what i should mention but i can show the Load Matrix window.

![screenshot from 2018-01-21 12-07-40](https://user-images.githubusercontent.com/6670911/35193506-e382357e-fea3-11e7-8bc6-61e260a05300.png)


Here, i have copied the matrices and renamed them, giving them the extension .matrix. They show up, but the 'old' ones - without the .matrix extension, do not show.

To compare, i checked it with your standalone Scanned Matrix Editor and there everythings is shown.

![screenshot from 2018-01-21 12-12-49](https://user-images.githubusercontent.com/6670911/35193557-9b4776a6-fea4-11e7-9252-6a604946eea0.png)

**Comment by kunstmusik** [comment]
Thanks for that, I tested on Linux and was able to reproduce the same
problem.  I then re-tested on Windows with the same folder of files and
found different results (the expected ones), so this looks like it is a
Linux-only issue.  I'll investigate and post a fix once it is ready, thanks!

**Comment by kunstmusik** [comment]
Fixed for 2.7.4.  (Test build is at http://kunstmusik.com/blue_2.7.4_dev.zip)
