### ISSUE TITLE
-96dB Mixer slider difference

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#390]
I have 2 Blue files attached (please remove the extra addition .txt from these files) showing that:

    an instrument with NO active volume AL is silent when, during playback, the fader of the mixer strip starts at position -96 dB and is then moved up
    same instrument WITH the volume AL active does in fact respond and works when the mixer strip starts at position -96 dB and is then moved up
[mixtestNoVolumeline.blue.txt](https://github.com/kunstmusik/blue/files/1651460/mixtestNoVolumeline.blue.txt)
[mixtestVolumeline.blue.txt](https://github.com/kunstmusik/blue/files/1651461/mixtestVolumeline.blue.txt)

i notice the issue when i manually move the sliders of the mixer from -96 dB upwards after having started playback.

**Comment by kunstmusik** [comment]
I figured out that when you say "the fader of the mixer strip starts at position -96 dB and is then moved up" this is not meaning the automation but moving the slider up.  I managed to reproduce the problem and I have an idea where the problem may be. Investigating now.

**Comment by kunstmusik** [comment]
Test build available at http://www.kunstmusik.com/blue_2.7.4_dev.zip
