### ISSUE TITLE
show name of marker

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#394]
![screenshot from 2018-02-05 15-11-51](https://user-images.githubusercontent.com/6670911/35808756-1c738cd6-0a87-11e8-93b5-c9bae47a8b84.png)

a name can be given to a marker. Can the marker itself show that name?

**Comment by kunstmusik** [comment]
I took a look at Ardour, Reaper, and Cakewalk for some ideas. All three use dedicate rows (Ardour calls it "rulers") above or below their time bars to show/edit markers.  The trouble with showing the name by the marker in the current Blue UI is that it would overlap the time text. 

I think a good solution then would be to redo the timebar and area above it to have a dedicated row for Markers, similar to what Ardour has. Right now Blue has just the tempo editor above the timeline. I can add a row for just the Markers next, then look at others in the future and follow Ardour's design to make it user configurable for what "rulers" to show. 

I'd like to do this as part of redoing the time display and controls area. I will push this to 2.7.5 and work on it after 2.7.4. goes out.

**Comment by tjingboem** [comment]
Yes i do think that this is a good solution. 
The top part of Ardour is a pretty busy area and takes a lot of space, so there is less space for the Objects. Better solution would be to be able to choose what an extra ruler should show.

![ardour](https://user-images.githubusercontent.com/6670911/83350614-8fda4380-a33d-11ea-9da1-ca634574b070.png)
  
Perhaps the yellow markers could stay where they are and the additional names could be part of a switchable row for 'Use Tempo' and 'Show Markernames'?

**Comment by kunstmusik** [comment]
Thanks for the screenshot, it's very useful coming back to this issue. Also thanks for the suggestion about a switchable row. I'll look at Blue's interface and see what I can come up with and reply when I have something to test.
