### ISSUE TITLE
zooming does not follow mouse pointer

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#399]
Zooming in or out on the TimeLine is done relative to the mouse pointer, but does not work here on Linux:
[zooming4-2018-04-07_13.38.40.mp4.zip](https://github.com/kunstmusik/blue/files/1886315/zooming4-2018-04-07_13.38.40.mp4.zip)

**Comment by tjingboem** [comment]
If i may suggest a possible way for zooming: https://www.reaper.fm/videos.php#rlF3oY0lEC4

**Comment by kunstmusik** [comment]
Thanks for the video link, the timeline needs a bit of a rewrite for sure.

**Comment by kunstmusik** [comment]
There's an issue when the zoom out shows the entire project and there is no scroll that when you zoom in things don't center on the mouse when the score size is still smaller than the scroll view. I think this will just be a known issue and a similar issue exists in other programs (e.g., Reaper).  Closing this out as done for 2.8.0.
