### ISSUE TITLE
set limit to temp files

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#402]
set limit to temp files to 10 for example

**Comment by tgrey1** [comment]
Alternate idea to achieve similar results, perhaps a setting that allows automatic cleanup after playback/render stops?

The temp files are useful when troubleshooting, but I could see wanting to avoid leaving them around entirely.

**Comment by kunstmusik** [comment]
Temps file limit setting added to General Settings panel in program options. Minimum 1, default of 3. Temp files are cleared when program ends unless Blue crashes (generally due to Csound crashing).
