### ISSUE TITLE
no 0 for p2 in JMask

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#403]
When, in the JMask Object, the value 0 for p2 is entered, Blue hangs.
So, prohibit the user for (accidentally) entering zero for p2.

**Comment by kunstmusik** [comment]
I modified this to check if Constant was used for p2 and if value was <= 0.0. If so, throw an error.  I think it gets a little more complicated to guess if user does things like uses an ItemList with only zeros, or random that only generates zeros, etc.  As a compromise, I think this will probably catch the easy errors.
