### ISSUE TITLE
refresh UI issue

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#416]
As reported on Slack on Wednesday October 15th 2018:

- in an older project, i exported an instrument (chorosynth.binstr)
- imported it in the present project
- the present project has already a few instruments,  with instr. 2 - 5
- the imported instrument becomes instr. 1 and in the Mixer something weird happens
*Mixer shows 2 times strip 5*
- i go back to the old project to copy in the MIxerstrip[ the effect that i need for this instrument
- i go to the new project to paste the effect and now the new Mixerstrip 1 has been created
- i can paste the effect into Mixerstrip #1
*everything back to normal*

Steven Yi: " Does look like a refresh problem. Not critical as I think a workaround would be to just change to a different project then change back which should reset the UI, but I can assign and look at for 2.7.4."

**Comment by tjingboem** [comment]
i think i found another case of a No Refresh Issue:
![Screenshot from 2019-07-14 18-18-12](https://user-images.githubusercontent.com/6670911/61186368-a2378a00-a664-11e9-91e6-8886df467b29.png)
Here i have removed 2 effects from 2 instruments. The drawn AL themselves are gone, but as you see the colored box  'JoyX' for the 1st instr. still exists and for instr.2 the blue 'JoyY'.
There is no way to get rid of them. 
I change to Orchestra and get back to the Score:
![Screenshot from 2019-07-14 18-28-19](https://user-images.githubusercontent.com/6670911/61186404-428dae80-a665-11e9-9b9d-e06d2a72eef6.png)
When i render, all renders well, but all the Layers are gone.

**Comment by kunstmusik** [comment]
I have fixed the original issue reported which was due to an incorrect insertion/event-firing code order when adding instruments that caused the mixer to add channels in the wrong places.  The second issue is really a separate issue but I will continue to look at it and track the change here.  

For the first issue, you're welcome to test and use the fixed version at https://kunstmusik.com/blue_2.7.4_dev.zip

**Comment by kunstmusik** [comment]
A couple of update issues were found for change listening for the set of automated parameters for a layer. This should resolve the second refresh issues reported. Please test at: https://kunstmusik.com/blue_2.7.4_dev.zip

Closing now, if further update issues found, please file new issues for each one to make it easier to track.  Thanks!
