### ISSUE TITLE
follow the green and yellow line

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#418]
Hitting F9 runs Blue from the Start Render Time.
1. can a jump to the green line where the piece starts rendering be implemented, by pressing for example F8?
2. a follow mode for the yellow playback head

**Comment by tjingboem** [comment]
1. green locator has shortcut "G"
2. screen does not follow the yellow playback head yet, but moves to the right outside the screen and visual contact is lost.

**Comment by kunstmusik** [comment]
Completed 'G' shortcut, rest being addressed in #484
