### ISSUE TITLE
re-install shortcuts for Score Mode, Single Mode and Multi Line Mode

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#431]
In the Blue manual i see:
alt-1     switch to Score mode
alt-2     switch to Single Line mode
alt-3     switch to Multi Line mode
but somewhere these shortcuts got lost.
can they be re-installed?

**Comment by kunstmusik** [comment]
@tjingboem I implemented this using just 1, 2, and 3 instead of having to use alt.  I was remembering that sometimes alt gets used on non-english keyboards for some characters and thought using 1, 2, and 3 directly would be fine. It should only work when the timeline has focus.  

Could you give https://kunstmusik.com/blue_2.7.4_dev.zip a try and see what you think?

**Comment by kunstmusik** [comment]
BTW: The above build is using Netbeans 10. Hopefully no issues, but let me know if there's anything strange you might see.

**Comment by tjingboem** [comment]
I could not get it to run however: menno@menno-P5K ~/bin/blue/bin $ ./blue
./blue: 69: ./../etc/blue.conf: Syntax error: Unterminated quoted string

**Comment by tjingboem** [comment]
Also i tried to add the desktop starter:
menno@menno-P5K ~/bin/blue/bin $ sh install_desktop_starter.sh 
[sudo] password for menno:           
Installed blue.desktop entry

i don't think i had to install the desktop starter before using the password...

After this installation with password there is no starter on my desktop

**Comment by kunstmusik** [comment]
I had to rebuild my Linux virtual machine to test but I could reproduce the problem. Looks to me that Netbeans 10 (and now tested and built with Netbeans 11) has a bug. I added a fix in Blue's build script and filed an issue with Netbeans (https://issues.apache.org/jira/browse/NETBEANS-2361). 

This build should work now:

https://kunstmusik.com/blue_2.7.4_dev.zip 

@tjingboem Could you retest this now?

**Comment by tjingboem** [comment]
we have a winner!
works great - same goes for 1,2 and 3, that are working and is working fast.
Thanks!

**Comment by kunstmusik** [comment]
Fantastic, thanks for verifying!  Closing out this issue now.
