### ISSUE TITLE
BlueShare confirmation dialogue window does not pop up easily

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#434]
Using BlueShare, i find that after deleting an old effect i have to do an extra mouse click before the Dialogue "are you sure etc." pops up. If i do not click, nothing haapens and the pop up window does not pop up.
Same for when i have uploaded a new one for the window "Effect succesfully received" i have to do an extra click

**Comment by kunstmusik** [comment]
Can not reproduce, will close for now. Please re-open with any further details if it appears again.
