### ISSUE TITLE
delete accidental remaining AL points after copying etc.

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#441]
![Screenshot from 2019-07-08 14-36-11](https://user-images.githubusercontent.com/6670911/60810798-351c8400-a18e-11e9-9e20-3d38d8e302b9.png)

Please notice the blue AL: it has 5 points.
after copying and/or deleting sometimes cluster of AL points remain on the same X axis (=time).
Is it not better to allow only 2 AL points to exist?
atm the remainders have to be deleted manually.

**Comment by kunstmusik** [comment]
Build posted to https://kunstmusik.com/blue_2.7.4_dev.zip.  The adjustment to clear out time dead points should now be made on paste, move, and individual point dragging.  It also deals with time zero points a little differently to make it easier to just click to add a point, drag to time zero, then have the new point take over for time zero.  

Let me know if there's any issues with this implementation, thanks!
