### ISSUE TITLE
UDO tab: rightclick menu is on the loose

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#443]
i copy an UDO from there and paste it in the UDO tab of my instrument, so that it becomes encapsulated
small thing i notice is when i rightclick the UDO i want to copy: the window appears on the bottom of the screen.
Does that with all UDOs in the UDO tab
![Screenshot from 2019-07-12 15-02-09](https://user-images.githubusercontent.com/6670911/61130736-b5f1bd80-a4b7-11e9-97ff-3693fab60f38.png)

**Comment by kunstmusik** [comment]
Testing here, the popup is always showing where I click, not necessarily above the selected item in the tree. Were you clicking on top of the selected item or towards the bottom?  This is the behavior I see for other trees in the application (i.e., Orchestra manager).  

I will test on Linux to see if it is the same there.

**Comment by tjingboem** [comment]
what i did:
i copied the text of tieStatus.udo from the Csound Journal and created a new UDO in BLue. Copied the text in etc. completed the work.

Now, tieStatus was at the bottom of the screen. i rightclicked on it to copy it and pasted itin the UDO tab of the instrument.
From that time on the menu has the odd behavior.

I just tried again: all works fine with the menu until i rightclick the UDO totally on the bottom of the UDO screen. The menu falls partially outside of the UDO container as you can see on the picture, From that moment on, no matter what UDO i click, the menu is way under the UDO i rightclick

**Comment by kunstmusik** [comment]
I think I found the problem, it happens here if I select an item, then scroll, then right click. It seems to calculate according to the virtual coordinates within the tree rather than the screen coordinate. I will look for the code causing the issue now.

**Comment by tjingboem** [comment]
i can confirm this when i copy your actions

**Comment by kunstmusik** [comment]
Found the source of problem and have pushed a fix. 

Testable in https://kunstmusik.com/blue_2.7.4_dev.zip

Thanks!
