### ISSUE TITLE
Single Line mode: weird AL movements on the left of marquee when snap is enabled

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#445]
as can be seen in the Csound Slack conversation from July 18th 2019 in video pointshift3-2019-07-18_11.10.17, moving AL points up and down inside the marquee influences the AL to the left of the selection.
I have noticed this behavior only when Snap was Enabled.

**Comment by kunstmusik** [comment]
Found some a couple of problems in the code so I redid a little bit how the code worked and added some additional checks for, and removal of, duplicate points.  I think it's a lot more robust and should be working cleanly now.  

Version to test available at https://kunstmusik.com/blue_2.7.4_dev.zip
