### ISSUE TITLE
Java error OS X 10.11.6

### ISSUE THREAD

**Issue by stuzog** [kunstmusik/blue#448]
Blue apparently starts up but no menu selections work; cannot start a new project. Log attached.

Product Version: Blue incubator-netbeans-release-404-on-20190319
Java: 11.0.1; OpenJDK 64-Bit Server VM 11.0.1+13
Runtime: OpenJDK Runtime Environment 11.0.1+13
System: Mac OS X version 10.13.6 running on x86_64; UTF-8; en_CA (blue)
User directory: /Users/stuart/Library/Application Support/blue/dev
Cache directory: /Users/stuart/Library/Application Support/blue/dev/var/cache
[messages.log](https://github.com/kunstmusik/blue/files/3443853/messages.log)

**Comment by kunstmusik** [comment]
Blue requires Java 8 (the message you have shows Java 11). As mentioned on the website:

"You will also need to install a 64-bit Java 8 JDK (Java Developer Kit) to run Blue. The recommended version is Oracle JDK 8. (OpenJDK is also suitable. Some Linux repositories package JavaFX separately from the main OpenJDK package. Be sure to install both openjdk and javafx.) Later versions of Java are not currently supported at this time (i.e, 9, 10, 11)."

Recommend downloading and installing Java 8. Oracle's Java 8 should work out of the box; I found OpenJDK 8 on OSX to not contain JavaFX which is necessary for Blue.  

Support for Java 11 is planned for Blue 2.8.0.

**Comment by stuzog** [comment]
Hi Steven,

Yes, I knew that, and did a fresh install of JDK 8 from the oracle site to make sure. The Java Control Panel show Java Version 8 Update 221 (build 1.8.0_221-b11) but the Blue About shows Java 11, which has me confused. How do I get Blue to run the installed Java?

Stuart




On July 29, 2019 at 1:19:44 PM, Steven Yi (notifications@github.com) wrote:

Blue requires Java 8 (the message you have shows Java 11). As mentioned on the website:

"You will also need to install a 64-bit Java 8 JDK (Java Developer Kit) to run Blue. The recommended version is Oracle JDK 8. (OpenJDK is also suitable. Some Linux repositories package JavaFX separately from the main OpenJDK package. Be sure to install both openjdk and javafx.) Later versions of Java are not currently supported at this time (i.e, 9, 10, 11)."

Recommend downloading and installing Java 8. Oracle's Java 8 should work out of the box; I found OpenJDK 8 on OSX to not contain JavaFX which is necessary for Blue.

Support for Java 11 is planned for Blue 2.8.0.

**Comment by kunstmusik** [comment]
Check out the second reply on this StackOverflow:

https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x

The one mentioning Info.plist. I'm guessing that you have Java 11 installed in addition to Java 8 and the system is opting to use that version as the default.

One option would be to do like the link above and disable Java 11 as a default. However, I have not tried this out as I only use Java 8 at the moment. Another option is a bit more cumbersome but you could edit the blue.app/Contents/Resources/blue/etc/blue.conf script and uncomment (remove the #) and define the javahome variable:

#jdkhome="/path/to/jdk"

Or try uninstalling Java 11 if you are not using it for other purposes. 

To figure out jdkhome, try typing this into the Terminal:

```/usr/libexec/java_home -V```

If the above doesn't clarify, paste the output of the java_home command here and I will try to assist further.

**Comment by stuzog** [comment]
Thanks, Steven! Disabling Java 11 did the trick. And for some reason, only CSound FLOSS manual opens from the Help menu.

Stuart


On July 29, 2019 at 1:54:31 PM, Steven Yi (notifications@github.com) wrote:

Check out the second reply on this StackOverflow:

https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x

The one mentioning Info.plist. I'm guessing that you have Java 11 installed in addition to Java 8 and the system is opting to use that version as the default.

One option would be to do like the link above and disable Java 11 as a default. However, I have not tried this out as I only use Java 8 at the moment. Another option is a bit more cumbersome but you could edit the blue.app/Contents/Resources/blue/etc/blue.conf script and uncomment (remove the #) and define the javahome variable:

#jdkhome="/path/to/jdk"

Or try uninstalling Java 11 if you are not using it for other purposes.

To figure out jdkhome, try typing this into the Terminal:

/usr/libexec/java_home -V

If the above doesn't clarify, paste the output of the java_home command here and I will try to assist further.

**Comment by kunstmusik** [comment]
I tested here and all of the manual links opened up in my browser
(Firefox). Are you using a different browser? Maybe there is an issue with
spaces in the paths if you have the blue.app located somewhere where the
path has a space?

**Comment by stuzog** [comment]
I’m using Opera, adding that to the Web browser list in Blue (blue?), which is at /Applications/Audio/CSound/blue.app, on the startup disk, which is “MBP 500”. I seem to remember reading somewhere in the docs that the docs had to be in the same directory as the app, but as it’s in the OS X app, it should find it?

Stuart


On July 30, 2019 at 7:09:29 AM, Steven Yi (notifications@github.com) wrote:

I tested here and all of the manual links opened up in my browser
(Firefox). Are you using a different browser? Maybe there is an issue with
spaces in the paths if you have the blue.app located somewhere where the
path has a space?
