### ISSUE TITLE
Scale AL points in Single Mode and Multi Mode using marquee

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#449]
Scaling of AL points (and Object) in Single and Multi Mode.

Right now, there is a choice in Multi Mode to let the marquee select AL points and, with Shift, also the underlying Object. This is great.

In Single or Multi Mode, the marquee (with Object selected or not) decides what has to be scaled; AL points only, or AL points AND Object

**Comment by kunstmusik** [comment]
Now implemented for 2.8.0
