### ISSUE TITLE
Java11 2.8.0dev:: Font in Java11 poses a slight problem in Score

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#469]
Font is slightly bigger with Java11:
![Screenshot from 2019-11-05 11-20-30](https://user-images.githubusercontent.com/6670911/68219560-80cd2600-ffe6-11e9-88eb-3d2ecbe5f517.png)

Quote Steven: 
"Font: On Mac it's always been 13pt but 12pt on other systems, but with Java 11 it looks like they changed the default font and I have some hardcoded sizes. 
Some of those I think I will replace with an Icon instead of text too as it will save visual space."

**Comment by kunstmusik** [comment]
Closing as this was reported fixed in later versions of Java.
