### ISSUE TITLE
Java11 2.8.0dev: devices drivers back to default?

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#475]
I found that since i am working with Java11 and Blue2.8.0dev, all settings from 2.7.4 were copied but not so the devices drivers. I think they are automatically reset to PortAudio and PortMidi
Did you notice something of the kind?

while i normally use Jack and Alsaseq for audio and midi

**Comment by kunstmusik** [comment]
Seems to have worked itself out and is not appearing now. Closing out issue.
