### ISSUE TITLE
Blue fails on FreeBSD: can't find blue-ext-openjfx even though openjfx8-devel-8.u202.b07_4,1 is installed

### ISSUE THREAD

**Issue by yurivict** [kunstmusik/blue#487]
Log: https://people.freebsd.org/~yuri/blue-build.log

**Comment by kunstmusik** [comment]
The error here is that the build was done using a Java 8 JDK and Java 11 is the minimum required for Blue 2.8.0. Closing as the result is as expected.

**Comment by yurivict** [comment]
It fails with exact same message when Java 11 is used.

**Comment by kunstmusik** [comment]
The error I see in the original log is:

```[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 11
Usage: javac <options> <source files>```

With references to openjdk8.  

If you could post a link to the log with Java 11, I can inspect it further.

**Comment by yurivict** [comment]
Full log with Java 11: https://people.freebsd.org/~yuri/blue-build-Java11.log

javac is now from Java11, and ```openjfx8-devel``` has been rebuilt with Java 11, but the failure still looks the same.

**Comment by kunstmusik** [comment]
openjfx8-devel should not be necessary with Blue latest as JavaFX was removed from JDK in Java 9; Blue's build now downloads and adds as part of the build process. I see this near the top:

```
===>   csound-blue-2.7.4.20200419 depends on file: /usr/local/openjdk11/bin/java - found
```

But no specific for javac.  I don't know BSD's Java setup, but maybe there needs to be something set to ensure javac from Java 11 is installed and used.

**Comment by yurivict** [comment]
> maybe there needs to be something set to ensure javac from Java 11 is installed and used.

javac is from Java 11.

**Comment by kunstmusik** [comment]
You shouldn't be getting:

```javac: invalid target release: 11```

If javac from Java 11 is being used.  I suspect that it might be installed but not what is being used by default on the system.  A call to ```mvn -v``` should say what version of Java is being used with maven.
