### ISSUE TITLE
Preset comments [sf#49]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#49]
I was thinking it would be nice to have a preset comments BSB widget that would allow one to enter notes specific to the preset. This would be useful for such information as suggested range of frequency or duration, and any other comments.

bw

**Comment by tjingboem** [comment]
i think this is already possible, in 2 different ways:
- use Add Label and fill in the text
- use Add Textfield so you can put your comments in the textfield.
![comments](https://cloud.githubusercontent.com/assets/6670911/22628003/749fe416-ebcc-11e6-8cde-abd09be8643e.png)

**Comment by kunstmusik** [comment]
I think comments could still be a nice thing for tooltips (text that shows
when you mouse over a widget).  The other two options are there and this
will add another for longer information and I think it can have its uses.

**Comment by kunstmusik** [comment]
I'm not sure how this would be useful as a widget.  Comments seem like it would be for the instrument as a whole for documenting things like frequency or things.  At least, as far as I understand what the request is. I am going to close out this one for now; if someone is continued to have interest in this, please open a new ticket.
