### ISSUE TITLE
BlueSynthBuilder widgets only running at i time

### ISSUE THREAD

**Issue by jason-timm** [kunstmusik/blue#491]
Since updating to Csound 6.14  (Blue 2.7.4), my BlueSynthBuilder instrument widget channels are only updating at i time and not k rate.

I'm on macOS 10.15.3.

**Comment by kunstmusik** [comment]
Are you using the API Renderer? (Under Preferences, Blue, Realtime Render). The 6.14 release had an issue where the Csound Java library was not present and a new version was released. It might be that the new version is also missing something.

**Comment by jason-timm** [comment]
I was using the API render if I remember correctly. I’m on the road now and will have to double check when I get home. 

Thanks
J

**Comment by jason-timm** [comment]
Hey Steven,

The API renderer in Blue had disappeared. So, I re-downloaded and installed Csound, set the render preference to API and all is well.

Thanks for the quick response.

Jason

**Comment by kunstmusik** [comment]
Ah great, I'll close this issue now. Cheers!
