### ISSUE TITLE
Unable to modify user defined sliders in piano roll

### ISSUE THREAD

**Issue by cianoc** [kunstmusik/blue#537]
In the new piano roll. I create a new field called HARSH. I add it to the note template and to the additional fields. I make it discrete. Min value 0 and Max value 10. Default value: 1

I then return to the sliders. When I select Harsh I can only set the slider to the min, or max values.

**Comment by kunstmusik** [comment]
Thanks for reporting, the code was properly listening to min/max range changes but didn't correctly set the value when just changing fields.  Should be all fixed up now.
