### ISSUE TITLE
Error running Blue for 1st time

### ISSUE THREAD

**Issue by frmaurer99** [kunstmusik/blue#551]
Hi! I just downloaded Blue and extracted the zip. Trying to run blue64.exe  or blue.exe I get the following error.
org.netbeans.InvalidException: StandardModule:com.kunstmusik.blue.plaf jarFile: F:\Programs\Blue\blue-windows-2.8.0\blue\blue\modules\com-kunstmusik-blue-plaf.jar: java.lang.UnsupportedClassVersionError: blue/plaf/Installer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I updated the Java runtime to the latest version (Java 8 271) but still get the same error.
Can you please help?
Thanks
Frank

**Comment by kunstmusik** [comment]
Hi Frank,

Blue requires a minimum of Java 11 (this is the current LTS release, the latest Java is 15).  There are instructions on the Blue site about this:

"You will also need to install a 64-bit Java 11+ JDK (Java Developer Kit) to run Blue. The recommended version is Java 11 from AdoptOpenJDK."

with a link to:

https://adoptopenjdk.net/

I think if you upgrade to Java 11 or greater (I have used on 11 and 15) it should solve the problem.

Let me know if that resolves it and I can close this issue.

All best!
Steven

**Comment by frmaurer99** [comment]
Hi Steven.
Sorry but no success so far.
I downloaded and installed the AdoptOpenJDK for the link in the mail and it
seemed to install OK. Tried to run Blue again but got the same error so I
uninstalled thye Java 8 runtime and JDK that I had on my machine. I then
restarted the machine. When I try to run Blue now I get the error Cannot
find Java 1.8 or higher.
I checked the AdoptOpenJDK ic located in C:\Program Files\AdoptOpenJdk. I
also looked at the AdoptOpenJDK website for information but could not find
any more info there either. Looks like BLUE  cant find the Java files.

Thanks
Frank

**Comment by kunstmusik** [comment]
Could you check your System Environment variables and see if you have a variable called JAVA_HOME set?  I have one as a user variable and it is set to:

C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot

I wonder if the AdoptOpenJDK installer did not set that for you for some reason?  You might try running the installer for AdoptOpenJDK once more now that the Java 8 runtime and JDK are removed, or setting the variable manually and point it to your specific JDK folder.

**Comment by frmaurer99** [comment]
Thanks for your response Steven!
Yes this environment variable exists and is like yours and points to where
the JDK is installed.

JAVA_HOME  C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\

I also ran java -version from the command prompt and got this:

C:\Users\frmau>java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

so as far as I can see the JDK is installed correctly.

Any idea?
Frank

**Comment by kunstmusik** [comment]
It's odd as this generally "just works". One simple thing to try is restarting the computer to ensure that environment variable are updated. (Might be silly but I figure doesn't hurt to try.) 

Another thing you can do is manually set which JDK you want Blue to use. If you edit the blue/etc/blue.conf file, you will find text near the bottom that is commented out:

```
# default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
#jdkhome="/path/to/jdk"
```

I think if you remove the hash and make it like so:

```
jdkhome="C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\"
```

it should work.  I'd give those a try and let me know if you continue to have problems.

**Comment by frmaurer99** [comment]
Steven,
Thank you very much!
I had restarted the computer twice already but setting jdkhome in the
config file worked so the program is starting as expected.
Now just the small matter of learning how to use it!

Thank you very much for your help. It is greatly appreciated. So many music
programs that are just a few years ol don't seem to be supported any more
and it's hard to get an answer if you run into problems (JMusic and JThon
Music for example). So thank you again very much

Frank

**Comment by frmaurer99** [comment]
Hi Steven

Really really sorry to get to you again!
I don't know if I am doing something really stupid but I just cant get the
program to work.
When I sent you the last email I got the program to open so I thought
everything is OK, but alas, when I tried to use it I got stuck again.
1) I looked at the manual in the folder where Blue is installed and I tried
to set the porogram options as it explains there, only there is no POptions
in the File menu. I found one in the Tools menu but it looks comtly
different to the one illustrated in the manual. It seems the Blue tab is
missing in the Options dialog. None of the options like Working dir, MIDI,
Rener etc are available. The tabs that I have are General, Editor, Fonts &
Colors, Keymap, Appearance and Miscellanious.

2) Then I tried to load an example file and I could not find a Load option
in the File menu. All I have there is Save, Save As and Save All (all
greyed out). The only option that is available is Page Setup. I tried to
consult the manual but that does not explain how to open a file and what
type of file to open so I'm relly stuck!

Really sorry to bother you again.

BTW I did delete my installation folder and then extracted the zip again.
My install directory is on a different drive as I could not extract the
files to the C: drive because of permissions. There is no dedicated
installer for the program, is that correct? All you need to do is extract
the zip using an extractor utility program?

Anyway tearing out my last greay hairs...

Thanks
Frank

**Comment by kunstmusik** [comment]
Glad to hear the program is starting up now!  I imagine the previous runs somehow corrupted the window settings for Blue. You can try deleting that, which on Windows should be in c:\Users\[your name]\AppData\Roaming\.blue\dev.  (Delete this while Blue is not on, then try starting Blue.)

**Comment by frmaurer99** [comment]
It worked. Thank you very much

Frank

**Comment by kunstmusik** [comment]
Glad to hear it!  Closing out this issue now.  Enjoy!
