### ISSUE TITLE
shortcuts for Follow Render Locator

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#558]
- add shortcut for Follow The Render Locator (Ctr+F ??)
- add shortcut for Options--> Playback --> Enable Follows Playback on Render Start (Alt+F ??)
- add both shortcut options in Options --> Keymap

**Comment by kunstmusik** [comment]
I added menu options under the Project menu to set the two options. These are in sync with the program options dialog and the F button in the main toolbar.  I did not add shortcuts by default as I think we need to be careful about overriding ctrl-f which is often used for find. However, you can set your own shortcut if you want to via Options --> Keymap.
