### ISSUE TITLE
Snap in Tempo

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#559]
Extend the snap of the Score to the Tempo, and react to the Snap On/Off of it

![Screenshot from 2020-12-22 19-45-36](https://user-images.githubusercontent.com/6670911/102926093-b9eb8280-4494-11eb-9fa9-1429439e7800.png)

**Comment by kunstmusik** [comment]
Snap seems to already be respected in terms of editing points. Is this request to enable snap shortcut (alt-s) and drawing of lines when snap is enabled?  BTW: I can move the snap shortcut to be a menu option under the Project menu so that it can be global.

**Comment by tjingboem** [comment]
yes, snap does work in Tempo, i just didn't notice it until now as i was working in a rather high resolution, and was not sure if the point i set on the Tempo line was at the right spot, relative to the PianoRolls i wanted to impose the Tempo change on.  Seeing the grid in the Tempo display can definitely help putting the points in the right place imho.
What might give anohter good reference is taking the value of the Time Display number ( in my case 5 ) and give each line 5 a bit thicker line- in the Score AND in the Tempo display
![Thick5](https://user-images.githubusercontent.com/6670911/102984372-c829b500-450d-11eb-83a4-5fd8a1be49ce.png)

In the example above, i notice just now the end time of the PianoRolls because i have set the Green locator at the end of the Objects concerned, that the point was NOT correctly set...

(Another approach entirely would be to have a crosshair option for the mouse so that points could be alligned in a simple and visual way...)

What happens when i come from Orchestra and go to the Score tab, then hit Alt+S right away, i get this menu activated:
![Screenshot from 2020-12-23 10-51-24](https://user-images.githubusercontent.com/6670911/102984561-0fb04100-450e-11eb-8276-67ba090303ed.png)
There is a clash. Would making ALT+S global solve this issue?  (personally i don't care about ALT+ xx to open up some file menu and can do well without it. This will free up all sorts of shortcut key options with ALT, like ALT+F for a Follow instruction.)

I am aware that now there are several different but connected issue in this one issue...if you'd like, we can split them into several ones.

**Comment by kunstmusik** [comment]
I added line drawing for the tempo editor when snap is enabled:
 
 
![image](https://user-images.githubusercontent.com/1622139/103243643-83948400-4928-11eb-919a-4b97f10bad4c.png)

I wasn't sure what else needs to be done for this issue to be closed? Some things seem like they could be new issues.

**Comment by tjingboem** [comment]
There are some issues on my system:

https://user-images.githubusercontent.com/6670911/103274701-8fcd1f80-49c2-11eb-99de-adf06938e308.mp4

When i create a point somewhere on the Line, i can create it freely on whatever spot i want; it does not snap immediately to the grid. Personally, i like this and can move the point over to a grid line when i want to. 
But not always...i think there are some rounding errors that make it snap to an imaginary grid line.
Up until now, i have seen this behavior only on the Timeline, not in the ALs.

**Comment by kunstmusik** [comment]
We could not reproduce the snap offset issue now so this item will be closed. If the bug appears again we can reopen a new issue.
