### ISSUE TITLE
"Not all children problem" Java in Win10

### ISSUE THREAD

**Issue by OvarbReivaj** [kunstmusik/blue#561]
Hi Steven, thanks for your wonderful software, I run it in win7 succesfully but I have problems now in a win10 system.
blue64 loads without warnings but with many menu items missing (no open text menu) so I cannot open projects.
I found just some warning lines at my IDE LOG at the end
"Not all children in Menu/Window/ marked with the position attribute: [blue-ui-filemanager-BlueFileManagerTopComponent.shadow], but some are: [org-netbeans-core-io-ui-IOWindowActio...."
 Any advice? thanks!!!
Complete Log here:

-------------------------------------------------------------------------------
>Log Session: Sunday, January 3, 2021 at 6:54:56 PM Argentina Standard Time
>System Info: 
  Product Version         = Blue 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 11.0.9; Java HotSpot(TM) 64-Bit Server VM 11.0.9+7-LTS; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 11.0.9+7-LTS
  Java Home               = C:\Program Files\Java\jdk-11.0.9
  System Locale; Encoding = es_AR (blue); Cp1252
  Home Directory          = C:\Users\javier
  Current Directory       = C:\Program Files\blue-windows-2.8.1\blue
  User Directory          = C:\Users\javier\AppData\Roaming\blue\dev
  Cache Directory         = C:\Users\javier\AppData\Local\blue\Cache\dev
  Installation            = C:\Program Files\blue-windows-2.8.1\blue\blue
                            C:\Program Files\blue-windows-2.8.1\blue\extra
                            C:\Program Files\blue-windows-2.8.1\blue\ide
                            C:\Program Files\blue-windows-2.8.1\blue\platform
                            C:\Program Files\blue-windows-2.8.1\blue\platform
  Boot & Ext. Classpath   = 
  Application Classpath   = C:\Program Files\blue-windows-2.8.1\blue\platform\lib\boot.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\lib\org-openide-modules.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\lib\org-openide-util-lookup.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\lib\org-openide-util-ui.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Program Files\blue-windows-2.8.1\blue\platform\core\asm-7.2.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\core\asm-commons-7.2.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\core\asm-tree-7.2.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\core\core-base.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\core\core.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\core\org-netbeans-libs-asm.jar;C:\Program Files\blue-windows-2.8.1\blue\platform\core\org-openide-filesystems.jar;C:\Program Files\blue-windows-2.8.1\blue\blue\core\locale\core_blue.jar
-------------------------------------------------------------------------------
INFO [blue.plaf.Installer]: Finished blue PLAF installation
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.41 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.util [9.15 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.util.ui [9.16 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.modules [7.56 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.annotations.common/1 [1.35 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.filesystems [9.18 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.awt [7.76 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.progress/1 [1.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.progress.nb [1.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.dialogs [7.50 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.nodes [7.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.windows [6.85 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.batik.read [1.1.0.1 1 netbeans-TLP/netbeans/release120-23-on-20200529]
	org.openide.util.ui.svg [1.1 netbeans-TLP/netbeans/release120-23-on-20200529]
	org.netbeans.modules.editor.mimelookup/1 [1.48 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.text [6.75 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.scripting [1.5 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.swing.tabcontrol [1.64 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.swing.outline [1.42 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.explorer [6.70 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.actions [6.47 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.queries/1 [1.51 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.templates [1.16 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.filesystems.nb [9.18 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.loaders [7.76 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.intent [1.10 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.io [1.11 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.io [1.57 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.openide.execution [9.11 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.swing.plaf [1.50 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.spi.quicksearch [1.35 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.settings/1 [1.65 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.util/1 [1.73 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.document [1.17.0.3 3 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.lexer/2 [1.71.0.1 1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.lib2/1 [2.28.0.55.3 55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.settings.lib [1.59.0.1 1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.fold/1 [1.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.indent/2 [1.51 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.guards/1 [1.41 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.lib/3 [4.15.0.23.3.55 23 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.spi.editor.hints/0 [1.50.0.7.55 7 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.asm [5.11 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.bootstrap/1 [2.86 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.startup.base [1.70.0.1 1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.startup/1 [1.70.0.1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.settings/1 [1.57 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.sampler [1.22 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.progress.ui [1.41 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.keyring [1.32 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core/2 [3.59 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.options.api/1 [1.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.options.keymap [1.45 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.settings.storage/1 [1.60.0.1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.fold.nbui [1.20.0.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor/3 [1.95.0.6.3.23.55 6 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.options.editor/1 [1.68 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.jna/2 [2.3 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs/2 [2.63.0.2 2 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs.windows [1.24 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs.ui [2.11.0.2 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.masterfs.nio2 [1.23 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.extexecution.base/2 [1.12 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.extexecution/2 [1.56 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.extbrowser/1 [1.61 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.api.search [1.29 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.completion/1 [1.52.0.2 2 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.search [1.33.0.0.55 0 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.plain.lib/1 [1.41 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.plain/2 [1.43 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.40 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.bracesmatching/0 [1.47.0.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.editor.actions/1 [1.39.0.55 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.modules.db.metadata.model/1 [1.19 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.jna.platform/2 [2.3 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.libs.flexmark [1.1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.windows/2 [2.93 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.ui/1 [1.53 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.output2/1 [1.50 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.network [1.20 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.nativeaccess/1 [1.39 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.multitabs/1 [1.20.0.1 1 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.io.ui/1 [1.38 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	org.netbeans.core.execution/1 [1.49 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241]
	com.kunstmusik.csound.manual [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.utilities [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.ext.commons.io [2.8.1 2.8.1 202012292259]
	com.kunstmusik.blue.ext.openjfx [1.0 2.8.1 202012292259]
	com.kunstmusik.blue.ui.utilities [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.ui.nbutilities [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.ui.filemanager [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.ui.components [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.plugin [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.plaf [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.osc [1.0 2.8.1 202012292301]
	com.kunstmusik.blue.midi [1.0 2.8.1 202012292300]
	com.kunstmusik.blue.ext.rhino [1.0 2.8.1 202012292259]
	com.kunstmusik.blue.ext.jython [1.0 2.8.1 202012292259]
	com.kunstmusik.blue.ext.exml [1.0 2.8.1 202012292259]
	com.kunstmusik.blue.ext.commons.lang3 [2.8.1 2.8.1 202012292259]
	com.kunstmusik.blue.branding [2.8.1 2.8.1 202012292259]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Windows
INFO [org.netbeans.core.network.proxy.windows.WindowsNetworkProxy]: Windows system proxy resolver: auto detect
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.openide.awt.Toolbar]: Too long AWTTask: 698 ms for org.openide.awt.Toolbar$Folder@32049319(FolderList{MultiFileObject@6fb9c6c1[Toolbars/UndoRedo]})
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
Diagnostic information
Input arguments:
	-Dnetbeans.user.dir=C:\Program Files\blue-windows-2.8.1\blue\bin
	-Djdk.home=C:\Program Files\Java\jdk-11.0.9
	-Dnetbeans.home=C:\Program Files\blue-windows-2.8.1\blue\platform
	-Dnetbeans.user=C:\Users\javier\AppData\Roaming\blue\dev
	-Dnetbeans.default_userdir_root=C:\Users\javier\AppData\Roaming\blue
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\javier\AppData\Roaming\blue\dev\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Dnetbeans.dirs=C:\Program Files\blue-windows-2.8.1\blue\blue;C:\Program Files\blue-windows-2.8.1\blue\extra;C:\Program Files\blue-windows-2.8.1\blue\ide;C:\Program Files\blue-windows-2.8.1\blue\platform
	exit
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 128,0MB maximum 2024,0MB
Non heap memory usage: initial 7,3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=11 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=6292 total loaded=6292 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 8.482.025.472
INFO [null]: Total physical memory 8.482.025.472
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/Window/ marked with the position attribute: [blue-ui-filemanager-BlueFileManagerTopComponent.shadow], but some are: [org-netbeans-core-io-ui-IOWindowAction.shadow, SwitchToRecentDocumentAction.shadow, Web, Tools, Separator3.instance, ConfigureWindow, org-netbeans-core-windows-actions-ResetWindowsAction.shadow, Separator4.instance, CloseWindowAction.shadow, CloseAllDocumentsAction.shadow, CloseAllButThisAction.shadow, GroupsMenuAction.shadow, DocumentsAction.shadow]
WARNING [org.openide.filesystems.Ordering]: Not all children in OptionsDialog/ marked with the position attribute: [BlueOptionsCategory], but some are: [Actions, Advanced, Appearance, Editor, Keywords, PreviewExamples, General.instance, Editor.instance, FontsAndColors.instance, Keymaps.instance, Appearance.instance, Advanced.instance]

**Comment by kunstmusik** [comment]
I'd suggest resetting your settings (dev) folder; see this comment and let me know if deleting the dev folder works:

https://github.com/kunstmusik/blue/issues/551#issuecomment-739416600

**Comment by OvarbReivaj** [comment]
It worked! All menu item are ok. Thanks Steven for your quick response! now I'm working in audio setup, I will read well the info here, thanks again!

**Comment by kunstmusik** [comment]
Glad to hear that is working now, enjoy!
