### ISSUE TITLE
Blue 2.8.1 on Windows 10

### ISSUE THREAD

**Issue by vertnik** [kunstmusik/blue#570]
Hi!

I installed Blue 2.8.1 on Windows 10, with AdoptOpenJDK 11.0.9.101 hotspot.
When Blue is started, some things are missing on the screen. For example
there are missing drop down menus in File menu, so I can not open files.

When I click on the File menu, the output of the Application Log returns
the following message:
"WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/Window/ marked with the position attribute: [blue-ui-filemanager-BlueFileManagerTopComponent.shadow], but some are: [org-netbeans-core-io-ui-IOWindowAction.shadow, SwitchToRecentDocumentAction.shadow, Web, Tools, Separator3.instance, ConfigureWindow, org-netbeans-core-windows-actions-ResetWindowsAction.shadow, Separator4.instance, CloseWindowAction.shadow, CloseAllDocumentsAction.shadow, CloseAllButThisAction.shadow, GroupsMenuAction.shadow, DocumentsAction.shadow]"

Here are the info about the Java version:
>System Info:
  Product Version         = Blue 12.0-631bd69cd6112b1cc4c892c24e3e605b1ba04241
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 11.0.9.1; OpenJDK 64-Bit Server VM 11.0.9.1+1; AdoptOpenJDK
  Runtime                 = OpenJDK Runtime Environment 11.0.9.1+1
  Java Home               = C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot

Br,

Robert
![Blue2 8 1](https://user-images.githubusercontent.com/37046879/105133026-34d3a780-5aec-11eb-92c6-822062176554.png)

**Comment by kunstmusik** [comment]
Hi Robert, 

Please try deleting your dev folder as mentioned in this comment:

https://github.com/kunstmusik/blue/issues/551#issuecomment-739416600

Let me know if that clears things up or if what happened after that.

All best,
Steven

**Comment by vertnik** [comment]
I can not find dev folder. I downloaded Blue 2.8.1 for windows, which is zip file.

Robert

**Comment by vertnik** [comment]
Steven, I founded dev folder. It was in AppData\Roaming.blue\dev. I deleted it and now Blue works normally.

Thank you,

Robert

**Comment by kunstmusik** [comment]
Glad to hear that's cleared up! Closing out this issue now.
