### ISSUE TITLE
JMask p field name gets lost

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#574]
a bit annoying issue in JMask: i give the p fields a name, but when i decide to Change Parameter Type, the name gets lost

https://user-images.githubusercontent.com/6670911/105388609-23d38500-5c17-11eb-8029-aa6788e40605.mp4

**Comment by kunstmusik** [comment]
Fixed in https://github.com/kunstmusik/blue/commit/fa309c01d55e789c2e27fe0b7200cf3c08839aa1
