### ISSUE TITLE
back from PolyObject to root gets me on a different spot in the comp

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#585]
Going from PolyObject back to Root gets me to a place other than that of the PolyObject.

https://user-images.githubusercontent.com/6670911/108421526-95fab200-7235-11eb-951f-17486392a57e.mp4

**Comment by kunstmusik** [comment]
@tjingboem Is this still happening? I wasn't able to reproduce this here.

**Comment by tjingboem** [comment]
i think this is fixed somehow. I will close the issue
