### ISSUE TITLE
LineMultiply set default 0 1 instead of 0 0

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#597]
i think its better to have the LineMultiply NP set default 0 1 instead of 0 0 ?

![Screenshot from 2021-04-02 17-00-14](https://user-images.githubusercontent.com/6670911/113505655-8cf14600-9540-11eb-89fe-47c33f18a08c.png)

now as a default, it is multplying by zero...

**Comment by kunstmusik** [comment]
Make sense to me, modified in roboto branch and will be released in 2.8.2.
