### ISSUE TITLE
no Solo in deeper level

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#604]
the Solo button does not work inside the PolyObject. I mean, when S is on, all other Objects just play along...
![Screenshot from 2021-05-07 12-43-46](https://user-images.githubusercontent.com/6670911/117471594-513f0700-af58-11eb-9edf-d483725a9ba8.png)
the mute button works.

**Comment by tjingboem** [comment]
This seems to work now.
Has something changed or is something repaired when moving to FlatLaf?

**Comment by kunstmusik** [comment]
I don't recall doing anything for this and it wouldn't have been affected by FlatLaf. If it's working, shall we close this ticket?

**Comment by tjingboem** [comment]
It is working now, also the Mute function works.
You can close the ticket.
