### ISSUE TITLE
drag a sample

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#615]
As a Reaper user, i am accustomed to drag the side of a Media object, and then this Object goes into repetition mode.
So i was dropping a sample on the Audio Layer and started dragging the sample so it would repeat itself- nothing happened of course.
![Screenshot from 2021-09-01 11-42-44](https://user-images.githubusercontent.com/6670911/131650251-f72dd425-55c4-41b5-909d-c18503a35c9f.png)
Is this something to have in Blue?

**Comment by kunstmusik** [comment]
AudioClip's now have a "Looping" property which is set to true by default. Can set to non-looping to get older behavior. Implemented for 2.8.2.
