### ISSUE TITLE
Jmask Object in PatternObject Layer Group

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#639]
### Discussed in https://github.com/kunstmusik/blue/discussions/638

<div type='discussions-op-text'>

<sup>Originally posted by **tjingboem** January 12, 2022</sup>
is there a reason for not having the Jmask Object available in the PatternObject Layer Group?

![Screenshot from 2022-01-12 10-27-22](https://user-images.githubusercontent.com/6670911/149105591-7ac142bc-35bc-477e-a704-1318a1837132.png)
</div>

**Comment by kunstmusik** [comment]
Completed in #638
