### ISSUE TITLE
Problem from Java after installation, not possible to launch Blue

### ISSUE THREAD

**Issue by stephaneboussuge** [kunstmusik/blue#643]
Here's the message I get:

org.netbeans.InvalidException: StandardModule:com.kunstmusik.blue.plaf jarFile: /Applications/blue.app/Contents/Resources/blue/blue/modules/com-kunstmusik-blue-plaf.jar: java.lang.UnsupportedClassVersionError: blue/plaf/Installer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 53.0

**Comment by kunstmusik** [comment]
The last release are a bit out of date unfortunately. Dev builds should
work and may be retrieved from Github actions. This one should run there:

https://github.com/kunstmusik/blue/actions/runs/1695895973

Be sure to use a Java 11 or greater JDK for running Blue. (The windows
version there includes the JDK with it; I will probably move to doing the
same for Mac). Hope to have some time starting in a couple of weeks to
resume dev work on Blue and Csound.

**Comment by stephaneboussuge** [comment]
Dear Steven,

Thank you, this one works well.

Best regards

Stéphane
