### ISSUE TITLE
thoughts on Swing for version 2.8.2

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#645]
i will give show some differences on the Roboto version of Blue. Because, as i understand it, reliable working with JavaFX in Blue cannot be trusted upon in the future, JavaFX will make room for Swing.

1. much faster, feel lighter in use, responds quicker
2. reliable for years to come

Converting existing instruments to Swing and Roboto:
1. here a comparison of the same instrument, designed with JavaFX
![JavaFX](https://user-images.githubusercontent.com/6670911/152650185-8d6d9cb3-4eeb-43a7-b02e-c251607690d5.png)
this is the Swing version:
![Swing](https://user-images.githubusercontent.com/6670911/152650200-a10da2a6-2240-4482-92e2-a9ba302de8c9.png)

Font and knobs are smaller.
Advantage IMO is that now there is more room for displaying more value numbers. That is useful
JavaFX: 
![JavaFXknobs](https://user-images.githubusercontent.com/6670911/152650351-5fb82a8c-5496-4bcb-8f1a-432bc7bb635e.png)
Swing:
![Swingknobs](https://user-images.githubusercontent.com/6670911/152650361-9d4a4736-67be-435a-9f54-4708d950bed4.png)

Advantage IMO of Roboto is the smaller and less bold type of font. This allows instruments and effects to become smaller.
And personally i don't mind redoing all my instrument and effects, now that i know that they will like that in 10 years from now...

A problem is that all sliders do not get the values like they were saved. I loose all presets and saved values in the blue files. 
Another thing is that the sliders are aesthetically not pleasing. Of course, IMO.

Then about the Editing response: it feels sluggish

https://user-images.githubusercontent.com/6670911/152651095-ef32d998-1104-4aaa-90cd-2d0189bd93e6.mp4

the sliders respond VERY fast, the knobs also. Nice also, that it is possible to be able to make fine adjustments with the knobs.

**Comment by tjingboem** [comment]
here an example of the sluggish way of editing:

https://user-images.githubusercontent.com/6670911/152651789-461b4a32-7434-483d-9379-108fadd3fa25.mp4

**Comment by kunstmusik** [comment]
@tjingboem I found the issue and fixed up the initial loading of values for horizontal and vertical sliders.  I will look at visual rendering of the slider next. Let me know if you encounter any further issues with the slider value loading.

**Comment by tjingboem** [comment]
here is a list of things that must be looked at:

- [ ] initial loading of values for horizontal and vertical sliders
- [ ] sluggish response when editing BSB
- [ ] change pointer arrow of sliders
- [ ] let the knobs show their label even if label is longer than width of knob 
![Screenshot from 2022-03-01 09-25-13](https://user-images.githubusercontent.com/6670911/156133698-8fba164b-68d9-46b8-87fb-784b3b7f99a4.png)
