### ISSUE TITLE
build not starting

### ISSUE THREAD

**Issue by muccio** [kunstmusik/blue#651]
latest build 2.8.1 (tried with different versions of java) on mac monterey always give:

_org.netbeans.InvalidException: StandardModule:com.kunstmusik.blue.plaf jarFile: /Users/.../blue.app/Contents/Resources/blue/blue/modules/com-kunstmusik-blue-plaf.jar: java.lang.UnsupportedClassVersionError: blue/plaf/Installer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0_

previous version (2.7.4) runs fine

**Comment by kunstmusik** [comment]
Java class version 52 is Java 8 and Java 11+ is required to run Blue. If
you have installed a version 11 Java then there must be a Java 8 version
that is still present.  Could you mention which Java you installed?

**Comment by muccio** [comment]
I have different versions (up to the latest release) and switching from command line to try to get it work, but still getting the same error

**Comment by kunstmusik** [comment]
Two things I can think of:

1. Try setting JAVA_HOME in your ~/.zshrc file to the location of a newer version of Java. For example, I have:

JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

2. Try the latest dev build. There is one here (requires logging in with github account):

https://github.com/kunstmusik/blue/actions/runs/2141672361

Note: I am going to look at making a version of Blue that has the JVM included (hopefully done this weekend) that may avoid this kind of problem in the future.

**Comment by muccio** [comment]
Unfortunately neither of this is working (path was already set to latest java release), dev build starts without giving error messages but tools and stuff is totally missing from the interface, same thing with the windows version, sounds like we are stuck with the old one.

**Comment by kunstmusik** [comment]
(Apologies for delay in reply) 

If the app is able to start, it may be an issue that the saved preferences are corrupt or incompatible with the latest version of Blue. Please try exiting Blue, deleting (or moving out of the way) the ~/Library/Application Support/blue/dev folder and starting Blue once again.

**Comment by muccio** [comment]
nope, unfortunately also after deleting the folder we still get:
org.netbeans.InvalidException: StandardModule:com.kunstmusik.blue.plaf jarFile: /private/var/folders/sy/8vv1vfsx0l51xpn8c3kqzy500000gn/T/AppTranslocation/2A9B57E7-273B-4DD0-8FED-56BDB7F603EB/d/blue.app/Contents/Resources/blue/blue/modules/com-kunstmusik-blue-plaf.jar: java.lang.UnsupportedClassVersionError: blue/plaf/Installer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by kunstmusik** [comment]
This message: 

"this version of the Java Runtime only recognizes class file versions up to 52.0"

Means it is using a Java 8 runtime. That is one problem that should prevent loading the app. The other problem is the app *does* load but the UI is messed up. 

Please try these two things:

1. Delete your Blue preferences (if on Windows, remove the c:\Users\[your username]\AppData\Roaming\blue folder)
2. Run one of the builds from https://github.com/kunstmusik/blue/actions/runs/2212867963

For MacOS, these builds now contain a Java installation and will ignore your local java installations; Windows build also includes Java and ignores local java installation.

**Comment by muccio** [comment]
you made it, everything seems to be ok, btw had to reset chmod permissions on monterey to make it work!
tnx buddy for being so kind in debugging!

**Comment by kunstmusik** [comment]
Glad that worked out in the end; hopefully after the next release these kinds of issues won't pop up again for anyone, but I'll see if I can add some info to the manual for this situation.
