### ISSUE TITLE
change aura of sliders

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#668]
The pointer takes a lot of space around it (aura), so it impossible to have 2 sliders close to each other as one slider cannot get selected alone

**Comment by kunstmusik** [comment]
@tjingboem Is this addressed with the the new FlatLAF work?

**Comment by tjingboem** [comment]
partially imo.
i am having issues with the 'aura' of the slider. I made a video about it.

https://user-images.githubusercontent.com/6670911/208398228-743e92d1-ac05-446b-813a-a112c22bcd9a.mp4

I do not know how close 2 sliders can get together before one is influencing the other, or if this aura is something you can define?

**Comment by kunstmusik** [comment]
The mouse areas should now be much closer to the thumb track on the slider bodies and allow users to overlap and get the sliders closer to each other.
