### ISSUE TITLE
let the knobs show entire label

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#669]
let the knobs show their label even if label is longer than width of knob
![Screenshot from 2022-03-01 09-25-13](https://user-images.githubusercontent.com/6670911/169363953-069f0d19-be3a-47da-82f8-0dd670f2c543.png)

**Comment by kunstmusik** [comment]
Knob editor now checks both knobWidth and label width when calculating the size of the component so that long labels will always show.
