### ISSUE TITLE
BSB Line Object screen does not get redrawn

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#671]
the screen does not get redrawn as you can see here:

https://user-images.githubusercontent.com/6670911/169365338-291cb4d9-2932-4475-84bf-17dd29eb5d32.mp4

**Comment by tjingboem** [comment]
i checked this again and It might well be part of the sluggish tempo when editing the BSBs on the Linux system:

https://user-images.githubusercontent.com/6670911/181281988-afe81611-405c-4837-8b17-5526f44f8701.mp4

that is a quirck on this system only as i understand from previous talks.

**Comment by tjingboem** [comment]
recently updated to Java17, but this issue still persists:

https://user-images.githubusercontent.com/6670911/187393219-5c2b54d0-a7fe-49fe-9704-49bad1de39ab.mp4

**Comment by tjingboem** [comment]
t only happens with the Line Object

https://user-images.githubusercontent.com/6670911/222145082-956bbad5-8014-425b-b389-f9c327047def.mp4

**Comment by kunstmusik** [comment]
I think this issue is now fixed as well as the situation where the line canvas would draw over other windows when it overlapped (though it should have been clipped). Please reopen this issue if you see it come up again, thanks!

**Comment by tjingboem** [comment]
i am pleased with the result but there is still a little issue.

https://user-images.githubusercontent.com/6670911/229076449-e7ab615c-ff78-463c-9083-f352db8c1be1.mp4


Here is a Blue file : 
[ModulatorModule7.blue.zip](https://github.com/kunstmusik/blue/files/11120166/ModulatorModule7.blue.zip)
