### ISSUE TITLE
bright blue for instrument selection

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#711]
in Flatlaf, a selected Instrument is bright blue. When changing the code a bit more, this bright blue color vanishes
and it is hard to see what Instrument i am working on.
Can a selected Instrument keep this bright blue color or will this cause issues for other selected things?

https://user-images.githubusercontent.com/6670911/208872407-2e4979c9-69d5-485a-8235-3632da072ba8.mp4

**Comment by tjingboem** [comment]
Here is another example where it might be nice to have confirmed by a brighter color that i am working in Stretcher --> sampleONCEstereo+ --> Code
![Screenshot from 2023-02-10 14-38-34](https://user-images.githubusercontent.com/6670911/218106134-98cd59f1-3130-4276-8679-6b4f2618ed61.png)
The words Stretcher and sampleONCEstereo+ could be brighter imo

**Comment by kunstmusik** [comment]
I made the background a little bit darker when the item is selected but the component is not in focus. I think technically it should be a little more of a contrast so that the eye sees the focused component a bit easier, but I think this is pretty good and should be an improvement.
