### ISSUE TITLE
Score, Single or Multi mode? not visible

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#712]
i find it a bit difficult to see when i am in Score, Single or Multi mode
![Screenshot from 2022-12-19 13-08-12](https://user-images.githubusercontent.com/6670911/209405247-e252c81b-e1fc-434d-9750-ebd9ac9fb295.png)

**Comment by kunstmusik** [comment]
Adjusted to a brighter blue color:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/1622139/217007504-b26cffea-0efd-4a51-9730-dd0b91102291.png">

I think eventually this should be replaced with icons and a grouped button bar, but will work on that in a separate issue.
