### ISSUE TITLE
google icons missing

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#713]
the new google arrows up and down are not everywhere yet
![Screenshot from 2022-12-19 13-14-07](https://user-images.githubusercontent.com/6670911/209405288-6ac35775-73ea-42ce-b564-1f5650ded4f3.png)
they are not yet implemented in the Note Processors in both the SoundObject NP and the Layer NP

**Comment by kunstmusik** [comment]
Completed, thanks!
