### ISSUE TITLE
blurring of the text when changing the text.

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#733]
https://user-images.githubusercontent.com/6670911/224123931-2a0aa794-7345-40c0-9241-7c4aff67ed57.mp4

**Comment by kunstmusik** [comment]
Is this still happening for you? I tried on macOS and couldn't reproduce, but I wonder if it is linux-specific.

**Comment by tjingboem** [comment]
i am afraid so
https://github.com/kunstmusik/blue/assets/6670911/7f9ec382-750f-4b75-8c78-d6a1eab370dd
