### ISSUE TITLE
Preset Manager of Instrument does not react

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#750]
https://github.com/kunstmusik/blue/assets/6670911/e034927e-2b39-432e-9b6f-f138d26c0183

**Comment by kunstmusik** [comment]
This is an odd one. I get a different issue on macOS where if I hit the menu it doesn't respond at all, similar to the issue with other popups that stop working. But if I navigate with keys and hit enter, it will remove and do other operations. I will have to try this on Linux to diagnose.

**Comment by kunstmusik** [comment]
So I have the same behavior on Linux as you do. I can, however, show the popup using the right click, then use the arrow keys and hit enter to trigger the action correctly. I think it's related to the other popup menus not responding issues. I will try to investigate this to finally figure out what is going on with FlatLAF.

**Comment by kunstmusik** [comment]
Fixed using odd hack to pass null as owner window to JDialog.
