### ISSUE TITLE
[Error] Score generation failed 

### ISSUE THREAD

**Issue by csounder5** [kunstmusik/blue#784]
When i run a blue file (On the sensation of tones) i get the message  [Error] Score generation failed

**Comment by kunstmusik** [comment]
If you go to the Tools menu and hit the "blue application log" menu option, do you see any additional error information in the log?

**Comment by csounder5** [comment]
As you see in the screenshot, there is nothing as"blue application log" in the Tool menu:
[cid:077c4618-1568-4802-a12c-2e12df786c05]

Also in other email  i sent you what you asked : "I need more information to diagnose. What OS? What version of Blue?
What version of Csound?"  here is again:

[cid:57f7f5cb-d054-4929-8491-0ac6dd7b134e]

________________________________

**Comment by kunstmusik** [comment]
I think something has gone wrong with github as I do not see any images in your reply.

**Comment by csounder5** [comment]
i sent all to  ***@***.***
________________________________

**Comment by kunstmusik** [comment]
Try using the github site for posting pictures, I think it will work better. 

Also, I was mistaken, the 'blue application log' is under the 'View' menu.

**Comment by csounder5** [comment]
Here attached is the log
________________________________

**Comment by kunstmusik** [comment]
@csounder5 I think the issue is one of permissions. It looks Blue is trying to write a temp file in the examples folder which might be write protected. Try copying the examples directory to somewhere like your home directory or desktop, then try opening the file from there, and let me know if that changes anything.

**Comment by csounder5** [comment]
It works!! Thanks
________________________________
