### ISSUE TITLE
Copies of an object that remains linked to the object [sf#84]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#84]
You can write a piece of score and then repeat it many times or copy it to different locations, but if later you decide to change it in every location it becomes a pain. It would be useful if you could chose whether to make a simple copy of an object which is then independent and can then be modified to be something else \(like now\) or a permanent copy which remains linked to the original object and is updated everytime you modify the original object

**Comment by tjingboem** [comment]
This is possibly an old request of mine...and perhaps obsolete?
Isn't this already possible with the SoundObject Library?

**Comment by kunstmusik** [comment]
Yes I believe so, let's close this one.
