### ISSUE TITLE
points selection on Automation Line [sf#93]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#93]
but now i want to select a few points and move those just a little to the right.
Shift-click does not work here.
It would be great to just use Shift and select another point so only selected points will move along with the way it is now already. At the moment all the points within the drawn window will get selected, also points from another Automation Line that has to stay in place.
I guess i need all these different functions now and then.

**Comment by tjingboem** [comment]
i think this one can be closed as they are available now in 2.6.1test4 and above?
